/**
 * Intentional rule violations for e2e tests. DO NOT edit this file by hand —
 * specs assert on specific byte offsets.
 *
 * Violations present (one per rule we care about):
 *   - rpc-only:    `.from("users")`
 *   - no-console:  `console.log(...)`
 *   - select-star: `.select("*")`
 *   - no-any:      `: any`
 *   - ts-ignore:   `// @ts-ignore`
 *
 * Each violation is on its own line so specs can target deterministic positions.
 */

// @ts-ignore intentional violation for ts-ignore rule
import type { Foo } from "nonexistent";

export async function badQuery(client: { from: (t: string) => unknown }) {
  const data: any = client.from("users"); // rpc-only + no-any
  console.log("queried users", data); // no-console
  return data;
}

export function selectStar(client: { from: (t: string) => { select: (s: string) => unknown } }) {
  return client.from("posts").select("*"); // select-star
}
