#!/usr/bin/env node
/**
 * Emit SQL that syncs acs_message_schemas.json_schema with the package schema
 * documents (source of truth). Used by the rollout runbook (enforce hygiene):
 *
 *   node packages/acs-contracts/scripts/copy-schemas.mjs > /tmp/acs_schema_sync.sql
 */
import { readdirSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const schemasDir = join(dirname(dirname(fileURLToPath(import.meta.url))), 'schemas');
const files = readdirSync(schemasDir).filter((f) => f.endsWith('.json'));

console.log('-- Generated by @aisha/acs-contracts scripts/copy-schemas.mjs — do not edit manually.');
console.log('BEGIN;');
for (const file of files) {
  const ref = file.replace(/\.json$/, '');
  if (ref === 'acs.envelope@1.0') continue; // envelope is validated by the SDK, not registered as a payload contract
  const doc = JSON.stringify(JSON.parse(readFileSync(join(schemasDir, file), 'utf8'))).replace(/'/g, "''");
  console.log(
    `UPDATE acs_message_schemas SET json_schema = '${doc}'::jsonb, updated_at = now() WHERE schema_ref = '${ref}';`,
  );
}
console.log('COMMIT;');
