#!/bin/bash
# =============================================================================
# PostgreSQL entrypoint wrapper — runs on EVERY container boot
# =============================================================================
# Re-applies role passwords (handles env var changes without recreating volume).
# Then delegates to the standard postgres entrypoint.
#
# Design (post-2026-05 hardening):
#   1. We no longer use `postgres --single` for password re-apply — that path
#      silently swallowed failures (e.g. exotic chars in password, postgres
#      single-user prompt quirks) and led to the "healthy DB but auth fails"
#      trap that consumed multiple deploy rounds debugging production cold-start.
#   2. Instead we kick off a background re-applier that waits for postmaster
#      to accept connections, then runs ALTER ROLE via psql with
#      ON_ERROR_STOP=1, and only touches /tmp/.db-passwords-ready once every
#      ALTER succeeded. The healthcheck waits for that sentinel, so dependent
#      services never see "healthy" before passwords are actually current.
#   3. /tmp/.db-passwords-ready is REMOVED on container start so a stale
#      sentinel from a previous run cannot mark a not-yet-applied DB healthy.
# =============================================================================
set -e

# Always invalidate the prior-run sentinel — we re-establish it after a
# successful password re-apply (or, on first init, after docker-entrypoint
# runs set-passwords.sh in /docker-entrypoint-initdb.d).
rm -f /tmp/.db-passwords-ready 2>/dev/null || true

# ── Verze dat × verze obrazu: nesoulad je STOP, ne pokus ─────────────────────
# Obraz nese PG_MAJOR i PGDATA z Dockerfilu (build-arg z POSTGRES_MAJOR instance).
# PostgreSQL by na datech jiné major verze sám odmítl start, ale hláškou, která
# neřekne, co dělat. A kdyby se PGDATA rozešlo s mountem, nastartoval by BEZ
# chyby prázdný cluster vedle dat (obraz pg18 má výchozí PGDATA jinde než pg17 —
# změřeno 2026-09-13). Obojí se zavírá tady, dřív než cokoli poběží.
: "${PG_MAJOR:?PG_MAJOR chybí v obrazu — Dockerfile ho musí nést (ARG → ENV)}"
: "${PGDATA:?PGDATA chybí v obrazu — Dockerfile ho musí nést výslovně}"
if [ -s "$PGDATA/PG_VERSION" ]; then
    DATA_MAJOR=$(tr -d '[:space:]' < "$PGDATA/PG_VERSION")
    if [ "$DATA_MAJOR" != "$PG_MAJOR" ]; then
        echo "postgres: FATAL — data v $PGDATA jsou PostgreSQL $DATA_MAJOR, obraz je PostgreSQL $PG_MAJOR." >&2
        echo "postgres: Změna major verze NENÍ restart: převod dump/restore (docs/deploy/POSTGRES_UPGRADE.md)," >&2
        echo "postgres: nebo vrať POSTGRES_MAJOR=$DATA_MAJOR v konfiguraci instance. Start odmítnut." >&2
        exit 1
    fi
fi

# Defensive: Coolify v4 stores env values with surrounding single quotes
# (real_value in API responses looks like "'WJQ…'"). When that literal value
# leaks into a container env, the runtime POSTGRES_PASSWORD becomes the
# 26-char `'WJQ…'` instead of the 24-char `WJQ…` that initdb hashed against.
# Strip a single layer of matching surrounding single OR double quotes from
# every secret before using it. No-op if the value is already unquoted.
strip_outer_quotes() {
    local v="$1"
    if [[ "$v" =~ ^\'(.*)\'$ ]] || [[ "$v" =~ ^\"(.*)\"$ ]]; then
        v="${BASH_REMATCH[1]}"
    fi
    printf "%s" "$v"
}

# ── Klíče šifrování: SOUBOR mimo databázi, NE GUC ────────────────────────────
# ⛔ NAMĚŘENO 2026-09-25 (dočasná DB, produkční příkaz): klíče dřív nesl
# `ALTER DATABASE postgres SET app.…` (+ PGOPTIONS) a vlastní GUC nejde omezit —
# přes current_setting() i pg_db_role_setting je přečetla KAŽDÁ role, i anon.
# Teď je zapíšeme sem (vlastník postgres, adresář 0700, soubor 0400) a SQL
# helpery aisha_column_encryption_key() / aisha_vault_encryption_key() je čtou
# pg_read_file jako vlastník. V GUC, katalogu ani záloze DB nejsou. Oba běhy
# (čistý initdb i existující data) potřebují soubory dřív, než kdo zavolá SQL,
# proto se píšou TADY, před větvením. Hodnota bajtově beze změny (printf '%s',
# bez konce řádku) — dosavadní šifrový text zůstává čitelný.
: "${VAULT_ENCRYPTION_KEY:?VAULT_ENCRYPTION_KEY must be set (generated by scripts/generate-secrets.mjs) — never a hardcoded default}"
: "${COLUMN_ENCRYPTION_KEY:?COLUMN_ENCRYPTION_KEY must be set (generated by scripts/generate-secrets.mjs) — never a hardcoded default}"
# Cesta je KONTRAKT se SQL helpery (čtou pevně /run/aisha-keys) — deklarovaná konstanta,
# ne dosazená záloha. Výslovný přepis jen pro brány, které wrapper pouštějí mimo kontejner
# (dočasný adresář); jiná hodnota v provozu = helper soubor nenajde a první šifrování
# spadne nahlas — klíč nikam tiše neuteče.
KLICE_DIR=/run/aisha-keys
if [ -n "${AISHA_KLICE_DIR:-}" ]; then
    KLICE_DIR=$AISHA_KLICE_DIR
fi
KLIC_TREZORU=$(strip_outer_quotes "$VAULT_ENCRYPTION_KEY")
KLIC_SLOUPCU=$(strip_outer_quotes "$COLUMN_ENCRYPTION_KEY")
if [ -z "$KLIC_TREZORU" ] || [ -z "$KLIC_SLOUPCU" ]; then
    echo "postgres: FATAL — klíč trezoru nebo sloupců je po odstranění uvozovek prázdný; start odmítnut." >&2
    exit 1
fi
zapis_klic() {  # <jméno souboru> <hodnota>
    local tmp
    tmp="$(mktemp "$KLICE_DIR/.$1.XXXXXX")"
    printf '%s' "$2" > "$tmp"
    chown postgres:postgres "$tmp"
    chmod 0400 "$tmp"
    mv -f "$tmp" "$KLICE_DIR/$1"
}
mkdir -p "$KLICE_DIR"
chown postgres:postgres "$KLICE_DIR"
chmod 0700 "$KLICE_DIR"
zapis_klic vault_encryption.key "$KLIC_TREZORU"
zapis_klic column_encryption.key "$KLIC_SLOUPCU"
# Procesy serveru klíče v prostředí nepotřebují (ani JWT secret, který DB
# nikdy nečetla) — pryč dřív, než se spustí postmaster.
unset KLIC_TREZORU KLIC_SLOUPCU VAULT_ENCRYPTION_KEY COLUMN_ENCRYPTION_KEY JWT_SECRET PGOPTIONS
echo "postgres: klíče šifrování zapsány do $KLICE_DIR (0400, postgres)."

# On a freshly-created data dir, docker-entrypoint.sh will run our
# set-passwords.sh init script which sets passwords AND touches the sentinel.
# No background re-applier needed.
if [ ! -s "$PGDATA/PG_VERSION" ]; then
    echo "postgres $PG_MAJOR: Fresh data dir — passwords will be set by /docker-entrypoint-initdb.d/002_set_passwords.sh"
    exec docker-entrypoint.sh "$@"
fi

# ── Existing data dir: schedule background psql re-apply once postmaster is ready ──
echo "postgres $PG_MAJOR: Existing data dir detected — scheduling post-start password re-apply."

# Normalize once, then escape for SQL.
RAW_POSTGRES_PASSWORD=$(strip_outer_quotes "${POSTGRES_PASSWORD:-}")

# Role a jejich hesla z JEDNOHO seznamu, sdíleného se set-passwords.sh (prvním
# initdb). Dřív tu byl druhý seznam s `:-$RAW_POSTGRES_PASSWORD` a bez
# postgres_exporter — heslo exporteru tak nenastavil nikdo (naměřeno
# 2026-09-19). Bez knihovny se nestartuje: re-apply bez hesel rolí by vypadalo
# jako zdravá DB.
HESLA_ROLI_LIB="$(dirname "$0")/hesla-roli.lib"
if [ ! -r "$HESLA_ROLI_LIB" ]; then
    echo "postgres: FATAL — chybí $HESLA_ROLI_LIB (seznam rolí a hesel)" >&2
    exit 1
fi
# shellcheck source=hesla-roli.lib
. "$HESLA_ROLI_LIB"
HESLA_SQL="$(hesla_roli_sql "$RAW_POSTGRES_PASSWORD")"
# Diagnostic: log the password length we're about to set (NOT the value).
# Helps confirm whether Coolify's quote-wrapping is in effect.
echo "postgres: POSTGRES_PASSWORD raw_len=${#POSTGRES_PASSWORD} stripped_len=${#RAW_POSTGRES_PASSWORD}"

# Refuse to start with an empty primary password — that's how we ended up
# with "auth failed for aisha_admin" while DB was "healthy".
if [ -z "${POSTGRES_PASSWORD:-}" ]; then
    echo "postgres: FATAL — POSTGRES_PASSWORD is empty; refusing to boot." >&2
    exit 1
fi

# ⛔ mktemp, NE pevná cesta (upstream 28de609c3, 2026-09-17): zastaralý
# /tmp/postgres-reapply.sql po nedoběhlém startu patří postgresovi s módem 600,
# takže `cat >` selže a kontejner se už nikdy nerozjede. `-t` respektuje $TMPDIR,
# takže testy nesdílejí soubor s jiným během.
REAPPLY_SQL="$(mktemp -t postgres-reapply.XXXXXX)"
cat > "$REAPPLY_SQL" <<EOSQL
\\set ON_ERROR_STOP on
${HESLA_SQL}
-- Klíče už nejsou GUC (soubory v /run/aisha-keys). Existující DB je drží
-- v pg_db_role_setting, dokud je výslovně nezrušíme; jwt_secret DB nikdy nečetla.
ALTER DATABASE postgres RESET app.settings.vault_encryption_key;
ALTER DATABASE postgres RESET app.column_encryption_key;
ALTER DATABASE postgres RESET app.settings.jwt_secret;
CREATE SCHEMA IF NOT EXISTS n8n;
ALTER SCHEMA n8n OWNER TO n8n_app;
GRANT CONNECT ON DATABASE postgres TO n8n_app;
GRANT CREATE ON DATABASE postgres TO n8n_app;
GRANT USAGE, CREATE ON SCHEMA n8n TO n8n_app;
EOSQL
chown postgres:postgres "$REAPPLY_SQL" 2>/dev/null || true
chmod 600 "$REAPPLY_SQL" 2>/dev/null || true

# Background re-applier — waits up to ~60s for postmaster, then runs ALTER ROLEs.
# Uses local socket auth (peer/trust on the postgres superuser via /var/run/postgresql),
# bypassing whatever stale TCP password may be in pg_authid for that role.
#
# CRITICAL: the sentinel `/tmp/.db-passwords-ready` is touched ONLY after we
# verify that the NEW password actually works via a fresh TCP password-auth
# connection — the same path clients (migrate, postgrest, etc.) use. This
# closes the window where ALTER ROLE returns 0 but PG's auth subsystem is
# still propagating the change, which historically caused dependents to see
# "FATAL: password authentication failed" on their FIRST psql call after
# healthcheck marked db healthy. (See migrate.mjs/seed.mjs retry loops —
# they were workarounds for this exact race; with this verify step the
# race window is sealed at the source.)
(
    for i in $(seq 1 30); do
        if pg_isready -h /var/run/postgresql -U postgres -d postgres -q 2>/dev/null; then
            echo "postgres: postmaster ready (attempt $i) — running ALTER ROLE re-apply…"
            if psql -h /var/run/postgresql -U postgres -d postgres \
                    -v ON_ERROR_STOP=1 -f "$REAPPLY_SQL" 2>&1; then
                rm -f "$REAPPLY_SQL"
                # CREATE DATABASE synapse cannot run inside the same script
                # if it's already wrapped in a transaction; do it separately,
                # idempotent.
                if ! psql -h /var/run/postgresql -U postgres -d postgres \
                        -tAc "SELECT 1 FROM pg_database WHERE datname='synapse'" \
                        2>/dev/null | grep -q 1; then
                    psql -h /var/run/postgresql -U postgres -d postgres \
                         -v ON_ERROR_STOP=1 \
                         -c "CREATE DATABASE synapse OWNER synapse_user ENCODING 'UTF8' LC_COLLATE 'C' LC_CTYPE 'C' TEMPLATE template0" \
                         2>&1 || echo "postgres: synapse db create skipped (likely already exists)."
                fi

                # ── Verify ALTER ROLE landed via TCP password-auth ─────────
                # Loop because pg's auth subsystem can take a small moment to
                # propagate after ALTER ROLE commits. Sentinel touched only
                # after a fresh TCP connection with the NEW password succeeds.
                echo "postgres: verifying new aisha_admin password via TCP auth…"
                verified=0
                for v in $(seq 1 15); do
                    if PGPASSWORD="$RAW_POSTGRES_PASSWORD" psql \
                            -h 127.0.0.1 -p 5432 -U aisha_admin -d postgres \
                            -tAc 'SELECT 1' 2>/dev/null | grep -q '^1$'; then
                        verified=1
                        echo "postgres: TCP password verify OK on attempt $v"
                        break
                    fi
                    sleep 1
                done
                if [ "$verified" != "1" ]; then
                    echo "postgres: ⚠ ALTER ROLE committed but TCP verify never succeeded within 15s — sentinel NOT touched." >&2
                    exit 1
                fi

                touch /tmp/.db-passwords-ready
                chmod 666 /tmp/.db-passwords-ready 2>/dev/null || true
                echo "postgres: Passwords re-applied successfully — sentinel /tmp/.db-passwords-ready touched."
                exit 0
            else
                echo "postgres: ALTER ROLE re-apply FAILED — leaving sentinel absent so dependents stay blocked." >&2
                exit 1
            fi
        fi
        sleep 2
    done
    echo "postgres: postmaster did not become ready within 60s — sentinel NOT touched." >&2
    exit 1
) &

# Delegate to standard entrypoint (which starts postmaster).
exec docker-entrypoint.sh "$@"
