-- Table: custom_node_registry
-- Purpose: Registry of all custom n8n nodes generated by NodeFactory
-- RLS: ENABLED

CREATE TABLE IF NOT EXISTS custom_node_registry (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  node_name text NOT NULL,
  display_name text NOT NULL,
  version text NOT NULL DEFAULT '0.1.0',
  description text,
  category text NOT NULL DEFAULT 'aisha',
  source_request_id uuid,
  package_json jsonb,
  is_active bool NOT NULL DEFAULT true,
  deployed_to_n8n bool NOT NULL DEFAULT false,
  n8n_node_type text,
  -- Provenance: NULL = node-factory or operator-declared node; non-NULL = materialized
  -- from an approved marketplace plugin (kind='automation_node'). Ownership guard —
  -- materialize_automation_node only updates a row it already owns.
  source_plugin_id uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id),
  CONSTRAINT custom_node_registry_source_plugin_id_fkey FOREIGN KEY (source_plugin_id) REFERENCES plugin_catalog(id) ON DELETE SET NULL,
  CONSTRAINT custom_node_registry_node_name_version_key UNIQUE (node_name, version),
  CONSTRAINT custom_node_registry_source_request_id_fkey FOREIGN KEY (source_request_id) REFERENCES node_factory_requests(id) ON DELETE SET NULL
);

ALTER TABLE custom_node_registry ENABLE ROW LEVEL SECURITY;
