-- ============================================================================
-- STEP 20: AISHA Backbone — Orchestration Layer Seed Data
-- Source of truth: Production Coolify DB (api.aisha.guru) + archived migrations
-- Generated by seed generator script v2
--
-- Order respects FK dependencies:
-- 1. guild_expertise_areas (no deps, 15 rows from production)
-- 2. context_profiles (no deps, 8 rows from production + learnings_enabled, K-26a)
-- 3. agent_catalog (refs context_profiles slug, 7 rows from production)
-- 4. integration_services (no deps, 6 rows — full stack incl. appsmith + github)
-- 5. delivery_transition_rules (no deps, 54 rows from production)
-- 6. ai_model_registry (no deps, 14 models from migrations)
-- 7. agent_tools (no deps, 6 tools from migrations)
-- 8. agent_tool_bindings (refs agent_configurations + agent_tools)
-- 9. ai_workflow_definitions (no deps, 2 pipelines from migrations)
-- 10. agent_decision_trees (refs agent_catalog, 3 trees from migrations)
-- ============================================================================

-- ============================================================================
-- guild_expertise_areas (15 rows from production)
-- ============================================================================
INSERT INTO public.guild_expertise_areas (
    id,
    slug,
    name_key,
    description_key,
    icon,
    parent_id,
    sort_order,
    is_active,
    created_at,
    updated_at
) VALUES (
    'f51eb361-40e7-4b0f-9c33-bb140858c08f',
    'frontend-development',
    'guild.expertise.frontend',
    'guild.expertise.frontend.desc',
    'monitor',
    NULL,
    10,
    true,
    '2026-03-08T10:28:00.455145+00:00',
    '2026-03-08T10:28:00.455145+00:00'
)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.guild_expertise_areas (
    id,
    slug,
    name_key,
    description_key,
    icon,
    parent_id,
    sort_order,
    is_active,
    created_at,
    updated_at
) VALUES (
    'd9afe3fa-4cc0-4ea7-9661-82ba92c341f3',
    'backend-development',
    'guild.expertise.backend',
    'guild.expertise.backend.desc',
    'server',
    NULL,
    20,
    true,
    '2026-03-08T10:28:00.455145+00:00',
    '2026-03-08T10:28:00.455145+00:00'
)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.guild_expertise_areas (
    id,
    slug,
    name_key,
    description_key,
    icon,
    parent_id,
    sort_order,
    is_active,
    created_at,
    updated_at
) VALUES (
    '8fc26b18-1c54-4c4f-8c89-268b1d5033c7',
    'fullstack',
    'guild.expertise.fullstack',
    'guild.expertise.fullstack.desc',
    'layers',
    NULL,
    30,
    true,
    '2026-03-08T10:28:00.455145+00:00',
    '2026-03-08T10:28:00.455145+00:00'
)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.guild_expertise_areas (
    id,
    slug,
    name_key,
    description_key,
    icon,
    parent_id,
    sort_order,
    is_active,
    created_at,
    updated_at
) VALUES (
    'd55df279-9f4f-42b7-9e80-2f0ad6a7ae43',
    'devops-infrastructure',
    'guild.expertise.devops',
    'guild.expertise.devops.desc',
    'cloud',
    NULL,
    40,
    true,
    '2026-03-08T10:28:00.455145+00:00',
    '2026-03-08T10:28:00.455145+00:00'
)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.guild_expertise_areas (
    id,
    slug,
    name_key,
    description_key,
    icon,
    parent_id,
    sort_order,
    is_active,
    created_at,
    updated_at
) VALUES (
    '693f45ca-308a-4ef8-8594-821eefb221b0',
    'database-design',
    'guild.expertise.database',
    'guild.expertise.database.desc',
    'database',
    NULL,
    50,
    true,
    '2026-03-08T10:28:00.455145+00:00',
    '2026-03-08T10:28:00.455145+00:00'
)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.guild_expertise_areas (
    id,
    slug,
    name_key,
    description_key,
    icon,
    parent_id,
    sort_order,
    is_active,
    created_at,
    updated_at
) VALUES (
    '950d42ab-f3de-4c85-b98d-a251258514d2',
    'ux-design',
    'guild.expertise.ux',
    'guild.expertise.ux.desc',
    'palette',
    NULL,
    60,
    true,
    '2026-03-08T10:28:00.455145+00:00',
    '2026-03-08T10:28:00.455145+00:00'
)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.guild_expertise_areas (
    id,
    slug,
    name_key,
    description_key,
    icon,
    parent_id,
    sort_order,
    is_active,
    created_at,
    updated_at
) VALUES (
    'db297f44-0c51-492d-adbc-ceb55c0085fc',
    'mobile-development',
    'guild.expertise.mobile',
    'guild.expertise.mobile.desc',
    'smartphone',
    NULL,
    70,
    true,
    '2026-03-08T10:28:00.455145+00:00',
    '2026-03-08T10:28:00.455145+00:00'
)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.guild_expertise_areas (
    id,
    slug,
    name_key,
    description_key,
    icon,
    parent_id,
    sort_order,
    is_active,
    created_at,
    updated_at
) VALUES (
    'f5e84e4e-1391-4974-abb6-65cbdbdfd7a9',
    'ai-machine-learning',
    'guild.expertise.ai',
    'guild.expertise.ai.desc',
    'brain',
    NULL,
    80,
    true,
    '2026-03-08T10:28:00.455145+00:00',
    '2026-03-08T10:28:00.455145+00:00'
)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.guild_expertise_areas (
    id,
    slug,
    name_key,
    description_key,
    icon,
    parent_id,
    sort_order,
    is_active,
    created_at,
    updated_at
) VALUES (
    '673bbb7d-cdf8-4841-a9a0-cc4334909d34',
    'security',
    'guild.expertise.security',
    'guild.expertise.security.desc',
    'shield',
    NULL,
    90,
    true,
    '2026-03-08T10:28:00.455145+00:00',
    '2026-03-08T10:28:00.455145+00:00'
)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.guild_expertise_areas (
    id,
    slug,
    name_key,
    description_key,
    icon,
    parent_id,
    sort_order,
    is_active,
    created_at,
    updated_at
) VALUES (
    '1ed320c9-3102-4ad7-8b3d-690a582753f5',
    'testing-qa',
    'guild.expertise.testing',
    'guild.expertise.testing.desc',
    'test-tube',
    NULL,
    100,
    true,
    '2026-03-08T10:28:00.455145+00:00',
    '2026-03-08T10:28:00.455145+00:00'
)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.guild_expertise_areas (
    id,
    slug,
    name_key,
    description_key,
    icon,
    parent_id,
    sort_order,
    is_active,
    created_at,
    updated_at
) VALUES (
    'abc6219d-f3ab-4837-905d-20748c24665a',
    'project-management',
    'guild.expertise.pm',
    'guild.expertise.pm.desc',
    'kanban',
    NULL,
    110,
    true,
    '2026-03-08T10:28:00.455145+00:00',
    '2026-03-08T10:28:00.455145+00:00'
)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.guild_expertise_areas (
    id,
    slug,
    name_key,
    description_key,
    icon,
    parent_id,
    sort_order,
    is_active,
    created_at,
    updated_at
) VALUES (
    'f7263088-3e62-44a6-8b6c-b9ca2f2a7488',
    'api-integrations',
    'guild.expertise.api',
    'guild.expertise.api.desc',
    'plug',
    NULL,
    120,
    true,
    '2026-03-08T10:28:00.455145+00:00',
    '2026-03-08T10:28:00.455145+00:00'
)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.guild_expertise_areas (
    id,
    slug,
    name_key,
    description_key,
    icon,
    parent_id,
    sort_order,
    is_active,
    created_at,
    updated_at
) VALUES (
    '24259816-0e4a-4b28-8a53-72a5e93317c6',
    'data-engineering',
    'guild.expertise.data',
    'guild.expertise.data.desc',
    'bar-chart',
    NULL,
    130,
    true,
    '2026-03-08T10:28:00.455145+00:00',
    '2026-03-08T10:28:00.455145+00:00'
)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.guild_expertise_areas (
    id,
    slug,
    name_key,
    description_key,
    icon,
    parent_id,
    sort_order,
    is_active,
    created_at,
    updated_at
) VALUES (
    'e6279a3f-cb02-4efa-ab95-09649a92797d',
    'blockchain-web3',
    'guild.expertise.blockchain',
    'guild.expertise.blockchain.desc',
    'link',
    NULL,
    140,
    true,
    '2026-03-08T10:28:00.455145+00:00',
    '2026-03-08T10:28:00.455145+00:00'
)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.guild_expertise_areas (
    id,
    slug,
    name_key,
    description_key,
    icon,
    parent_id,
    sort_order,
    is_active,
    created_at,
    updated_at
) VALUES (
    '266ed6e7-559f-4d0b-bdd8-21b621559510',
    'performance-optimization',
    'guild.expertise.performance',
    'guild.expertise.performance.desc',
    'zap',
    NULL,
    150,
    true,
    '2026-03-08T10:28:00.455145+00:00',
    '2026-03-08T10:28:00.455145+00:00'
)
ON CONFLICT (slug) DO NOTHING;

-- ============================================================================
-- context_profiles (8 rows from production)
-- ============================================================================
INSERT INTO public.context_profiles (
    id,
    slug,
    display_name,
    description,
    layers,
    token_budget,
    priority_order,
    is_active,
    created_at
) VALUES (
    'd1426f25-8b31-4bf7-a486-0e89a38d2f4d',
    'rules_only',
    'Rules Only',
    'Minimal context for compliance gates: only ruleset + basic story metadata.',
    '{
  "memory": {
    "enabled": false
  },
  "ruleset": {
    "enabled": true,
    "max_rules": 50,
    "include_body": true
  },
  "kb_retrieval": {
    "enabled": false
  },
  "project_context": {
    "fields": [
      "story"
    ],
    "enabled": true
  }
}'::jsonb,
    4000,
    ARRAY['ruleset', 'project_context']::text[],
    true,
    '2026-03-08T10:28:00.91127+00:00'
)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.context_profiles (
    id,
    slug,
    display_name,
    description,
    layers,
    token_budget,
    priority_order,
    is_active,
    created_at
) VALUES (
    '0bf3bc12-874a-4bfa-944c-ac407f52b231',
    'repo_plus_rules',
    'Repo + Rules',
    'Standard dev context: project files + ruleset + KB coding standards + recent memory.',
    '{
  "memory": {
    "enabled": true,
    "max_events": 10
  },
  "ruleset": {
    "enabled": true,
    "max_rules": 20,
    "include_body": false
  },
  "kb_retrieval": {
    "enabled": true,
    "item_types": [
      "expert_rule",
      "engineering_doc"
    ],
    "max_chunks": 10,
    "similarity_threshold": 0.3
  },
  "project_context": {
    "fields": [
      "story",
      "ruleset",
      "build_config",
      "env_hints"
    ],
    "enabled": true
  }
}'::jsonb,
    8000,
    ARRAY['governance_context', 'psyche_context', 'ruleset', 'project_context', 'kb_retrieval', 'memory']::text[],
    true,
    '2026-03-08T10:28:00.91127+00:00'
)
ON CONFLICT (slug) DO NOTHING;

-- ⭐ learnings_enabled (2026-09-29, SELF_IMPROVEMENT_LOOP.md K-26a, rozhodnutí majitele D7).
-- Výchozí profil běhů reflexe: svc-ai-chat reflection/orchestrator.ts:182, contextLoader.ts:27
-- a nodes/hippocampus.ts:42 ho berou, když běh profil neurčí — ale v seedu ani SoT NEBYL.
-- compose_context tak při každém běhu reflexe spadl na „Context profile not found", runner
-- chybu jen zalogoval a běh jel úplně BEZ kontextu (bez pravidel, KB i paměti); vrstva
-- naučeného se nikdy nevyhledala, takže fn_maybe_promote_learning neměla co počítat.
-- Tvar = repo_plus_rules (výchozí profil agentů) + vrstva `learnings`. Vyhledání naučeného
-- potřebuje embedding naučeného i dotazu (K-26b/c) — do té doby vrstva nic nevrátí, ostatní
-- vrstvy fungují hned. ON CONFLICT DO NOTHING: instance, která si profil už založila, si ho drží.
INSERT INTO public.context_profiles (
    id,
    slug,
    display_name,
    description,
    layers,
    token_budget,
    priority_order,
    is_active,
    created_at
) VALUES (
    '1e70be12-e1e0-4232-aa33-d037e4e192e3',
    'learnings_enabled',
    'Reflection + Learnings',
    'Default context for reflection runs: ruleset + project + KB + recent memory + learned pattern→resolution memories.',
    '{
  "memory": {
    "enabled": true,
    "max_events": 10
  },
  "ruleset": {
    "enabled": true,
    "max_rules": 20,
    "include_body": false
  },
  "learnings": {
    "enabled": true,
    "max_learnings": 5,
    "min_importance": 3
  },
  "kb_retrieval": {
    "enabled": true,
    "item_types": [
      "expert_rule",
      "engineering_doc"
    ],
    "max_chunks": 10,
    "similarity_threshold": 0.3
  },
  "project_context": {
    "fields": [
      "story",
      "ruleset",
      "build_config",
      "env_hints"
    ],
    "enabled": true
  }
}'::jsonb,
    8000,
    ARRAY['governance_context', 'psyche_context', 'ruleset', 'project_context', 'kb_retrieval', 'learnings', 'memory']::text[],
    true,
    '2026-09-29T00:00:00+00:00'
)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.context_profiles (
    id,
    slug,
    display_name,
    description,
    layers,
    token_budget,
    priority_order,
    is_active,
    created_at
) VALUES (
    'aed6fb5c-234b-496a-994d-113660df4613',
    'planning_heavy',
    'Planning Heavy',
    'Architecture/roadmap work: full ruleset + product principles + deep KB search + extended memory.',
    '{
  "memory": {
    "enabled": true,
    "max_events": 30
  },
  "ruleset": {
    "enabled": true,
    "max_rules": 30,
    "include_body": true
  },
  "kb_retrieval": {
    "enabled": true,
    "item_types": [
      "expert_rule",
      "domain_doc",
      "playbook"
    ],
    "max_chunks": 20,
    "similarity_threshold": 0.25
  },
  "project_context": {
    "fields": [
      "story",
      "ruleset",
      "build_config",
      "participants"
    ],
    "enabled": true
  }
}'::jsonb,
    16000,
    ARRAY['governance_context', 'psyche_context', 'project_context', 'ruleset', 'kb_retrieval', 'memory']::text[],
    true,
    '2026-03-08T10:28:00.91127+00:00'
)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.context_profiles (
    id,
    slug,
    display_name,
    description,
    layers,
    token_budget,
    priority_order,
    is_active,
    created_at
) VALUES (
    '83efb784-deba-4126-919a-065160b8f9b8',
    'evidence_strict',
    'Evidence Strict',
    'Ground-truth only: published rules + internal docs. No memory. For verification/audit.',
    '{
  "memory": {
    "enabled": false
  },
  "ruleset": {
    "enabled": true,
    "max_rules": 50,
    "include_body": true
  },
  "kb_retrieval": {
    "enabled": true,
    "item_types": [
      "expert_rule",
      "engineering_doc"
    ],
    "max_chunks": 15,
    "similarity_threshold": 0.4
  },
  "project_context": {
    "fields": [
      "story",
      "ruleset"
    ],
    "enabled": true
  }
}'::jsonb,
    12000,
    ARRAY['governance_context', 'psyche_context', 'ruleset', 'kb_retrieval', 'project_context']::text[],
    true,
    '2026-03-08T10:28:00.91127+00:00'
)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.context_profiles (
    id,
    slug,
    display_name,
    description,
    layers,
    token_budget,
    priority_order,
    is_active,
    created_at
) VALUES (
    '2d3b717d-c205-4a10-925a-b95e39729bde',
    'chat_lightweight',
    'Chat Lightweight',
    'Conversational context for chat interactions: slim KB search + short memory.',
    '{
  "memory": {
    "enabled": true,
    "max_events": 15
  },
  "ruleset": {
    "enabled": false
  },
  "kb_retrieval": {
    "enabled": true,
    "item_types": [
      "expert_rule",
      "faq"
    ],
    "max_chunks": 5,
    "similarity_threshold": 0.35
  },
  "project_context": {
    "fields": [
      "story"
    ],
    "enabled": true
  }
}'::jsonb,
    4000,
    ARRAY['psyche_context', 'kb_retrieval', 'memory', 'project_context']::text[],
    true,
    '2026-03-08T10:28:00.91127+00:00'
)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.context_profiles (
    id,
    slug,
    display_name,
    description,
    layers,
    token_budget,
    priority_order,
    is_active,
    created_at
) VALUES (
    '11ee6511-5685-43d8-8358-6914832e9e8c',
    'incident_response',
    'Incident Response',
    'Debugging/incident: full project context + error-focused KB + extended memory for trace.',
    '{
  "memory": {
    "enabled": true,
    "max_events": 50
  },
  "ruleset": {
    "enabled": true,
    "max_rules": 10,
    "include_body": false
  },
  "kb_retrieval": {
    "enabled": true,
    "item_types": [
      "expert_rule",
      "engineering_doc",
      "incident_report"
    ],
    "max_chunks": 15,
    "similarity_threshold": 0.3
  },
  "project_context": {
    "fields": [
      "story",
      "ruleset",
      "build_config",
      "env_hints"
    ],
    "enabled": true
  }
}'::jsonb,
    12000,
    ARRAY['governance_context', 'psyche_context', 'memory', 'project_context', 'kb_retrieval', 'ruleset']::text[],
    true,
    '2026-03-08T10:28:00.91127+00:00'
)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.context_profiles (
    id,
    slug,
    display_name,
    description,
    layers,
    token_budget,
    priority_order,
    is_active,
    created_at
) VALUES (
    'fff60269-f6d7-4681-95ab-1ee268bde4f5',
    'chat_default',
    'Chat Default',
    'Standard chat context with ruleset awareness, broader KB search, and memory. Used by ai-chat as primary context profile when compose_context is the system prompt source (Phase 0.3).',
    '{
  "memory": {
    "enabled": true,
    "max_events": 15
  },
  "ruleset": {
    "enabled": true,
    "max_rules": 10,
    "include_body": false
  },
  "kb_retrieval": {
    "enabled": true,
    "item_types": [
      "expert_rule",
      "faq",
      "domain_doc"
    ],
    "max_chunks": 8,
    "similarity_threshold": 0.3
  },
  "project_context": {
    "fields": [
      "story"
    ],
    "enabled": true
  }
}'::jsonb,
    8000,
    ARRAY['governance_context', 'psyche_context', 'kb_retrieval', 'ruleset', 'memory', 'project_context']::text[],
    true,
    '2026-03-14T22:18:39.573112+00:00'
)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.context_profiles (
    id,
    slug,
    display_name,
    description,
    layers,
    token_budget,
    priority_order,
    is_active,
    created_at
) VALUES (
    '9e8bdc2c-3536-41a5-8d40-ea690d31b38c',
    'dirigent_full',
    'Dirigent Full Context',
    'Full context bundle for Dirigent moderation sessions. Includes rulesets, project context, knowledge retrieval, and memory. Ruleset-first priority ensures compliance rules always fit within budget.',
    '{
  "memory": {
    "enabled": true,
    "max_events": 20
  },
  "ruleset": {
    "enabled": true,
    "max_rules": 30,
    "include_body": true
  },
  "kb_retrieval": {
    "enabled": true,
    "max_chunks": 10,
    "similarity_threshold": 0.7
  },
  "project_context": {
    "fields": [
      "tech_stack",
      "delivery_status",
      "risk_profile",
      "domain"
    ],
    "enabled": true
  }
}'::jsonb,
    16000,
    ARRAY['governance_context', 'psyche_context', 'ruleset', 'project_context', 'kb_retrieval', 'memory']::text[],
    true,
    '2026-03-08T10:28:01.518948+00:00'
)
ON CONFLICT (slug) DO NOTHING;

-- ============================================================================
-- agent_catalog (7 rows from production)
-- ============================================================================
INSERT INTO public.agent_catalog (
    id,
    slug,
    display_name,
    purpose,
    default_model,
    model_overrides,
    allowed_tools,
    denied_tools,
    default_context_profile,
    max_loops,
    safety_level,
    is_active,
    created_at,
    updated_at,
    autonomy_level
) VALUES (
    '989ce855-2608-4208-b831-ca9a5cd794cd',
    'dirigent',
    'Dirigent — Development Flow Moderator',
    'moderation',
    'gpt-strong',
    '{}'::jsonb,
    ARRAY['search_knowledge_v2', 'get_knowledge_item', 'get_story_context', 'get_expertise_areas', 'get_expert_rule', 'validate_compliance', 'moderate_flow', 'evaluate_tests', 'assess_quality', 'suggest_next_step', 'estimate_effort', 'check_pr_compliance']::text[],
    ARRAY['scaffold_story', 'deploy_environment']::text[],
    'dirigent_full',
    5,
    'strict',
    true,
    '2026-03-08T10:28:01.516276+00:00',
    '2026-03-15T14:24:16.683244+00:00',
    'manual'
)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.agent_catalog (
    id,
    slug,
    display_name,
    purpose,
    default_model,
    model_overrides,
    allowed_tools,
    denied_tools,
    default_context_profile,
    max_loops,
    safety_level,
    is_active,
    created_at,
    updated_at,
    autonomy_level
) VALUES (
    'ecf87ca2-db03-4296-959f-b2d9e7e4c688',
    'dev_patch',
    'Dev Patch Agent',
    'patching',
    'code_strong',
    '{
  "fast": "gemini-2.5-flash",
  "low_risk": "gemini-2.5-flash",
  "high_risk": "gpt-4o",
  "deep_analysis": "gpt-4o"
}'::jsonb,
    ARRAY['search_knowledge_v2', 'get_knowledge_item', 'get_story_context', 'get_expert_rule']::text[],
    ARRAY['deploy_environment']::text[],
    'repo_plus_rules',
    3,
    'standard',
    true,
    '2026-03-08T10:28:00.905391+00:00',
    '2026-03-15T14:24:16.774075+00:00',
    'semi'
)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.agent_catalog (
    id,
    slug,
    display_name,
    purpose,
    default_model,
    model_overrides,
    allowed_tools,
    denied_tools,
    default_context_profile,
    max_loops,
    safety_level,
    is_active,
    created_at,
    updated_at,
    autonomy_level
) VALUES (
    '9e5089bb-5893-47ee-b8de-94a7cdec6587',
    'debug_agent',
    'Debug Agent',
    'debugging',
    'reasoning',
    '{
  "fast": "gemini-2.5-flash",
  "low_risk": "gemini-2.5-flash",
  "high_risk": "gpt-4o",
  "deep_analysis": "gpt-4o"
}'::jsonb,
    ARRAY['search_knowledge_v2', 'get_knowledge_item', 'get_story_context']::text[],
    ARRAY['scaffold_story', 'deploy_environment']::text[],
    'repo_plus_rules',
    3,
    'standard',
    true,
    '2026-03-08T10:28:00.905391+00:00',
    '2026-03-15T14:24:16.776117+00:00',
    'semi'
)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.agent_catalog (
    id,
    slug,
    display_name,
    purpose,
    default_model,
    model_overrides,
    allowed_tools,
    denied_tools,
    default_context_profile,
    max_loops,
    safety_level,
    is_active,
    created_at,
    updated_at,
    autonomy_level
) VALUES (
    'b5030d9d-a425-4ed2-91e8-41c2bd870e00',
    'verifier',
    'Verifier',
    'verification',
    'reasoning',
    '{
  "fast": "gemini-2.5-flash",
  "low_risk": "gpt-5-mini",
  "high_risk": "gpt-4o",
  "deep_analysis": "gpt-4o"
}'::jsonb,
    ARRAY['search_knowledge_v2', 'get_knowledge_item', 'validate_compliance', 'get_story_context']::text[],
    ARRAY['scaffold_story', 'deploy_environment']::text[],
    'evidence_strict',
    2,
    'strict',
    true,
    '2026-03-08T10:28:00.905391+00:00',
    '2026-03-15T14:24:16.776903+00:00',
    'manual'
)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.agent_catalog (
    id,
    slug,
    display_name,
    purpose,
    default_model,
    model_overrides,
    allowed_tools,
    denied_tools,
    default_context_profile,
    max_loops,
    safety_level,
    is_active,
    created_at,
    updated_at,
    autonomy_level
) VALUES (
    '27dacb22-83a9-4adf-8b8b-017c016a2649',
    'aisha_planner',
    'Aisha Planner',
    'planning',
    'claude-opus',
    '{
  "fast": "gemini-2.5-flash",
  "low_risk": "gemini-2.5-flash",
  "high_risk": "gpt-4o",
  "deep_analysis": "gpt-4o"
}'::jsonb,
    ARRAY['search_knowledge_v2', 'get_knowledge_item', 'get_story_context', 'get_expertise_areas', 'match_experts', 'get_knowledge_stats']::text[],
    ARRAY['scaffold_story', 'deploy_environment']::text[],
    'planning_heavy',
    5,
    'strict',
    false,
    '2026-03-08T10:28:00.905391+00:00',
    '2026-03-15T14:24:16.771716+00:00',
    'manual'
)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.agent_catalog (
    id,
    slug,
    display_name,
    purpose,
    default_model,
    model_overrides,
    allowed_tools,
    denied_tools,
    default_context_profile,
    max_loops,
    safety_level,
    is_active,
    created_at,
    updated_at,
    autonomy_level
) VALUES (
    'f2caab8c-f484-416e-9776-2a52f6ebfde9',
    'compliance_gate',
    'Compliance Gate',
    'compliance',
    'reasoning',
    '{
  "fast": "gemini-2.5-flash",
  "low_risk": "gpt-5-mini",
  "high_risk": "gpt-4o",
  "deep_analysis": "gpt-4o"
}'::jsonb,
    ARRAY['search_knowledge_v2', 'get_knowledge_item', 'validate_compliance', 'get_story_context']::text[],
    ARRAY['scaffold_story', 'deploy_environment']::text[],
    'rules_only',
    1,
    'strict',
    true,
    '2026-03-08T10:28:00.905391+00:00',
    '2026-03-15T14:24:16.77495+00:00',
    'manual'
)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.agent_catalog (
    id,
    slug,
    display_name,
    purpose,
    default_model,
    model_overrides,
    allowed_tools,
    denied_tools,
    default_context_profile,
    max_loops,
    safety_level,
    is_active,
    created_at,
    updated_at,
    autonomy_level
) VALUES (
    '4384a1f6-b27d-41d1-8c22-305a87255fa9',
    'librarian',
    'Knowledge Librarian',
    'documentation',
    'gemini-2.5-flash',
    '{
  "fast": "gemini-2.5-flash",
  "low_risk": "gemini-2.5-flash",
  "high_risk": "gpt-5-mini",
  "deep_analysis": "gpt-5-mini"
}'::jsonb,
    ARRAY['search_knowledge_v2', 'get_knowledge_item', 'get_knowledge_stats', 'get_expertise_areas']::text[],
    ARRAY['scaffold_story', 'deploy_environment', 'validate_compliance']::text[],
    'evidence_strict',
    2,
    'minimal',
    true,
    '2026-03-08T10:28:00.905391+00:00',
    '2026-03-15T14:24:16.775529+00:00',
    'full'
)
ON CONFLICT (slug) DO NOTHING;

-- occipitum (visual design agent). Restored into the seed from the archived
-- 20260412100000_occipitum_design_profiles.sql migration under the baseline-only
-- policy: its KB is seeded in 30_occipitum_design_kb.sql and it has a dedicated
-- integrity gate, but the agent_catalog row itself was never carried into the
-- SoT/seed — so a fresh DB would never register the agent. Column set matches the
-- rows above; values are from that migration (id/timestamps stamped here since the
-- migration let them default).
INSERT INTO public.agent_catalog (
    id,
    slug,
    display_name,
    purpose,
    default_model,
    model_overrides,
    allowed_tools,
    denied_tools,
    default_context_profile,
    max_loops,
    safety_level,
    is_active,
    created_at,
    updated_at,
    autonomy_level
) VALUES (
    'b8e0c7a4-9f3d-4c21-a6e8-1d2f3a4b5c6d',
    'occipitum',
    'Occipitum',
    'Visual design agent — generates innovative, personality-profiled GrapeJS canvas designs. '
      || 'Processes design DNA interviews, creates canvas proposals via randomness-injected KB search, '
      || 'and learns partner aesthetic preferences through Hippocampus personality signals.',
    'claude-sonnet-4-5',
    '{}'::jsonb,
    ARRAY['search_knowledge', 'search_knowledge_v2', 'get_design_profile', 'upsert_design_profile', 'store_agent_memory', 'search_ragnarok', 'compose_context']::text[],
    ARRAY[]::text[],
    'planning_heavy',
    5,
    'standard',
    true,
    '2026-04-12T10:00:00+00:00',
    '2026-04-12T10:00:00+00:00',
    'semi'
)
ON CONFLICT (slug) DO NOTHING;

-- ============================================================================
-- integration_services (6 rows — full stack for local dev/AISHA self-management)
-- ============================================================================
INSERT INTO public.integration_services (
    id,
    service_name,
    display_name,
    service_type,
    base_url,
    api_token,
    config,
    health_status,
    last_health_check,
    is_active,
    managed_by,
    created_at,
    updated_at
) VALUES (
    '309771ef-0802-4e0d-ab53-a5e4ef90acc8',
    'nocodb',
    'NocoDB',
    'admin_bridge',
    'https://${NOCODB_DOMAIN}',
    NULL,
    '{
  "description": "Spreadsheet-like admin interface for AISHA PostgreSQL analytics views"
}'::jsonb,
    'healthy',
    now(),
    true,
    'aisha',
    '2026-03-08T10:28:02.156718+00:00',
    '2026-03-08T10:28:02.156718+00:00'
)
ON CONFLICT (service_name) DO NOTHING;

INSERT INTO public.integration_services (
    id,
    service_name,
    display_name,
    service_type,
    base_url,
    api_token,
    config,
    health_status,
    last_health_check,
    is_active,
    managed_by,
    created_at,
    updated_at
) VALUES (
    '7fa95ba2-3fcd-4c68-ac27-1db15adc4ebf',
    'langfuse',
    'Langfuse',
    'observability',
    'https://${LANGFUSE_DOMAIN}',
    NULL,
    '{
  "sso_enabled": true,
  "embed_enabled": false,
  "context_sync_enabled": false,
  "project_id": "aisha-dirigent",
  "description": "LLM observability, tracing and analytics"
}'::jsonb,
    'healthy',
    now(),
    true,
    'aisha',
    '2026-03-08T10:28:02.156718+00:00',
    '2026-03-08T10:28:02.156718+00:00'
)
ON CONFLICT (service_name) DO NOTHING;

INSERT INTO public.integration_services (
    id,
    service_name,
    display_name,
    service_type,
    base_url,
    api_token,
    config,
    health_status,
    last_health_check,
    is_active,
    managed_by,
    created_at,
    updated_at
) VALUES (
    'e3e26b9c-8c8f-4e03-abec-edcfdcf07317',
    'n8n',
    'n8n Workflow Engine',
    'automation',
    'https://${N8N_DOMAIN}',
    NULL,
    '{
  "sso_enabled": true,
  "embed_enabled": false,
  "context_sync_enabled": false,
  "description": "Workflow automation engine for Aisha Dirigent"
}'::jsonb,
    'healthy',
    now(),
    true,
    'aisha',
    '2026-03-08T10:28:02.156718+00:00',
    '2026-03-08T10:28:02.156718+00:00'
)
ON CONFLICT (service_name) DO NOTHING;

INSERT INTO public.integration_services (
    id,
    service_name,
    display_name,
    service_type,
    base_url,
    api_token,
    config,
    health_status,
    last_health_check,
    is_active,
    managed_by,
    created_at,
    updated_at
) VALUES (
    '84722249-8d55-4bef-baf1-b6adf5778d3a',
    'health',
    'Health Monitor',
    'monitoring',
    'https://${N8N_DOMAIN}',
    NULL,
    '{
  "description": "Aggregated health checks for all integration services"
}'::jsonb,
    'healthy',
    now(),
    true,
    'aisha',
    '2026-03-08T10:28:02.301072+00:00',
    '2026-03-08T10:28:02.301072+00:00'
)
ON CONFLICT (service_name) DO NOTHING;

INSERT INTO public.integration_services (
    service_name,
    display_name,
    service_type,
    base_url,
    api_token,
    config,
    health_status,
    last_health_check,
    is_active,
    managed_by
) VALUES (
    'appsmith',
    'Appsmith',
    'admin_bridge',
    'https://${APPSMITH_DOMAIN}',
    NULL,
    '{
  "sso_enabled": true,
  "embed_enabled": true,
  "context_sync_enabled": true,
  "app_id": "69cdf9824c99c02ecad13a0e",
  "embed_url": "https://${APPSMITH_DOMAIN}/app/storyloop-dashboard-1-69cdf9824c99c02ecad13a0e/page-69cdf9824c99c02ecad13a10",
  "embed_path": "https://${APPSMITH_DOMAIN}/app/storyloop-dashboard-1-69cdf9824c99c02ecad13a0e/page-69cdf9824c99c02ecad13a10",
  "description": "Low-code admin dashboard for StoryLoop",
  "workspace_id": "69cdf0f34c99c02ecad139fb"
}'::jsonb,
    'healthy',
    now(),
    true,
    'aisha'
)
ON CONFLICT (service_name) DO NOTHING;

INSERT INTO public.integration_services (
    service_name,
    display_name,
    service_type,
    base_url,
    api_token,
    config,
    health_status,
    last_health_check,
    is_active,
    managed_by
) VALUES (
    'github',
    'GitHub',
    'scm',
    'https://api.github.com',
    NULL,
    '{
  "description": "GitHub REST API — git hosting, PRs and commit statuses for AISHA self-management (GitHub Enterprise: set base_url to https://<host>/api/v3)"
}'::jsonb,
    'healthy',
    now(),
    true,
    'aisha'
)
ON CONFLICT (service_name) DO NOTHING;

-- ============================================================================
-- delivery_transition_rules (54 rows from production)
-- ============================================================================
INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    1,
    NULL,
    'analyzing',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    2,
    'analyzing',
    'matched',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    3,
    'analyzing',
    'blocked',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    4,
    'matched',
    'scaffolding',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    5,
    'matched',
    'blocked',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    6,
    'scaffolding',
    'ready',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    7,
    'scaffolding',
    'blocked',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    8,
    'ready',
    'in_progress',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    9,
    'ready',
    'blocked',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    10,
    'in_progress',
    'qa',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    11,
    'in_progress',
    'blocked',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    12,
    'qa',
    'delivering',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    13,
    'qa',
    'in_progress',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    14,
    'qa',
    'blocked',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    15,
    'delivering',
    'delivered',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    16,
    'delivering',
    'blocked',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    17,
    'delivered',
    'archived',
    'staff',
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    18,
    'delivered',
    'maintenance',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    19,
    'maintenance',
    'in_progress',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    20,
    'maintenance',
    'archived',
    'staff',
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    21,
    'blocked',
    'analyzing',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    22,
    'blocked',
    'matched',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    23,
    'blocked',
    'scaffolding',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    24,
    'blocked',
    'ready',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    25,
    'blocked',
    'in_progress',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    26,
    'blocked',
    'qa',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    27,
    NULL,
    'analyzing',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    53,
    NULL,
    'analyzing',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    79,
    NULL,
    'analyzing',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    105,
    NULL,
    'analyzing',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    131,
    NULL,
    'analyzing',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    157,
    NULL,
    'analyzing',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    183,
    NULL,
    'analyzing',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    209,
    NULL,
    'analyzing',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    235,
    NULL,
    'analyzing',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    261,
    NULL,
    'analyzing',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    287,
    NULL,
    'analyzing',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    313,
    NULL,
    'analyzing',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    339,
    NULL,
    'analyzing',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    365,
    NULL,
    'analyzing',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    391,
    NULL,
    'analyzing',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    417,
    NULL,
    'analyzing',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    443,
    NULL,
    'analyzing',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    469,
    NULL,
    'analyzing',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    495,
    NULL,
    'analyzing',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    521,
    NULL,
    'analyzing',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    547,
    NULL,
    'analyzing',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    573,
    NULL,
    'analyzing',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    599,
    NULL,
    'analyzing',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    625,
    NULL,
    'analyzing',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    651,
    NULL,
    'analyzing',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    677,
    NULL,
    'analyzing',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    703,
    NULL,
    'analyzing',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.delivery_transition_rules (
    id,
    from_status,
    to_status,
    requires_role,
    is_active
) VALUES (
    729,
    NULL,
    'analyzing',
    NULL,
    true
)
ON CONFLICT (id) DO NOTHING;

-- ⛔ Sekvence za pevnými id (naměřeno 2026-09-14): řádky výše nesou id z produkce,
-- sekvence ale zůstala na začátku → první INSERT bez id (admin, migrace, test) na
-- čisté instanci padl na delivery_transition_rules_pkey. Posun jen DOPŘEDU
-- (max(id) i dosavadní last_value), idempotentní. Sekvence jménem přes ::regclass,
-- NE pg_get_serial_sequence(): ta pro sekvenci bez OWNED BY vrací NULL a setval(NULL)
-- by potichu nic neudělal. Týž příkaz je v heals.sql pro běžící instance.
-- Hlídá src/tests/db/sekvence-nezaostava-za-daty.runtime.test.ts.
SELECT setval(
  'public.delivery_transition_rules_id_seq'::regclass,
  GREATEST(
    (SELECT COALESCE(max(id), 0) FROM public.delivery_transition_rules),
    (SELECT COALESCE(last_value, 0) FROM pg_sequences
      WHERE schemaname = 'public' AND sequencename = 'delivery_transition_rules_id_seq'),
    1),
  EXISTS (SELECT 1 FROM public.delivery_transition_rules)
    OR EXISTS (SELECT 1 FROM pg_sequences
      WHERE schemaname = 'public' AND sequencename = 'delivery_transition_rules_id_seq' AND last_value IS NOT NULL)
);

-- ============================================================================
-- ai_model_registry (14 models from archived migrations)
-- ============================================================================
-- cached_input_price_per_m = prompt-cache READ rate (odysseus G1). Sourced from
-- public provider pricing (2026-07-08). Per-provider cache-read discount vs base
-- input rate:
--   anthropic → 0.10× (90% off; write is 1.25× and is not stored — costAggregator
--               falls back to input for writes). Sources: platform.claude.com/docs/pricing
--   openai    → 0.10× current-gen (gpt-5/o-series per developers.openai.com/api/docs/pricing),
--               0.50× legacy gpt-4o family, 0.25× o-mini reasoning tier.
--   google    → 0.10× Gemini 2.5+ (ai.google.dev/gemini-api/docs/pricing), 0.25× 2.0.
--   xai       → ~0.15× (aipricing.guru/xai-pricing; grok is eval_status=pending, approximate).
--   vllm/local→ 0 (self-hosted, no per-token cost).
-- These are cold-start DEFAULTS; the discovery scan (upsert_discovered_model, now
-- carrying p_cached_input_price_per_m) is authoritative and overrides going forward.
-- Live DBs are backfilled by heals.sql (ON CONFLICT DO NOTHING won't touch existing rows).
INSERT INTO public.ai_model_registry (provider, model_id, display_name, model_family, is_reasoning, is_vision, is_function_calling, context_window, max_output_tokens, input_price_per_m, output_price_per_m, cached_input_price_per_m, eval_status) VALUES
  -- OpenAI
  ('openai', 'gpt-5-mini', 'GPT-5 Mini', 'gpt-5', true, false, true, 128000, 16384, 0.1500, 0.6000, 0.0150, 'approved'),
  ('openai', 'gpt-4o', 'GPT-4o', 'gpt-4o', false, true, true, 128000, 16384, 2.5000, 10.0000, 1.2500, 'approved'),
  ('openai', 'gpt-4o-mini', 'GPT-4o Mini', 'gpt-4o', false, true, true, 128000, 16384, 0.1500, 0.6000, 0.0750, 'approved'),
  ('openai', 'o4-mini', 'O4 Mini', 'o4', true, true, true, 200000, 100000, 1.1000, 4.4000, 0.2750, 'tested'),
  ('openai', 'o3-mini', 'O3 Mini', 'o3', true, false, true, 200000, 100000, 1.1000, 4.4000, 0.2750, 'tested'),
  -- Anthropic (cache read 0.10× base input)
  ('anthropic', 'claude-sonnet-4-20250514', 'Claude Sonnet 4', 'claude-4', false, true, true, 200000, 16384, 3.0000, 15.0000, 0.3000, 'approved'),
  ('anthropic', 'claude-3-5-sonnet-20241022', 'Claude 3.5 Sonnet', 'claude-3.5', false, true, true, 200000, 16384, 3.0000, 15.0000, 0.3000, 'approved'),
  ('anthropic', 'claude-3-5-haiku-20241022', 'Claude 3.5 Haiku', 'claude-3.5', false, false, true, 200000, 8192, 0.8000, 4.0000, 0.0800, 'tested'),
  -- Google / Gemini
  ('google', 'gemini-2.5-flash', 'Gemini 2.5 Flash', 'gemini-2.5', true, true, true, 1048576, 65536, 0.1500, 0.6000, 0.0150, 'approved'),
  ('google', 'gemini-2.5-pro', 'Gemini 2.5 Pro', 'gemini-2.5', true, true, true, 1048576, 65536, 1.2500, 10.0000, 0.1250, 'tested'),
  ('google', 'gemini-2.0-flash', 'Gemini 2.0 Flash', 'gemini-2.0', false, true, true, 1048576, 8192, 0.1000, 0.4000, 0.0250, 'approved'),
  -- xAI / Grok (approximate; eval pending)
  ('xai', 'grok-3', 'Grok 3', 'grok-3', true, false, true, 131072, 16384, 3.0000, 15.0000, 0.4500, 'pending'),
  ('xai', 'grok-3-mini', 'Grok 3 Mini', 'grok-3', true, false, true, 131072, 16384, 0.3000, 0.5000, 0.0450, 'pending')
ON CONFLICT (provider, model_id) DO NOTHING;

-- vLLM self-hosted
-- ⛔ is_available = FALSE (2026-09-13). Lokální řádek neříká „tenhle model běží",
-- říká „tenhle model znám". Dostupný se stane, až ho discovery uvidí v ÚPLNÉM
-- živém listingu providera (svc-ai-chat modelDiscovery → upsert_discovered_model);
-- dokud tam není, `mark_models_unavailable` ho tam drží. Naměřeno: řádek stál
-- is_available=true na instancích, kde ho nic neobsluhovalo, a resolver ho nabízel.
INSERT INTO public.ai_model_registry (
  provider, model_id, display_name, model_family,
  is_chat_capable, is_reasoning, is_vision, is_code_optimized, is_function_calling,
  context_window, max_output_tokens,
  input_price_per_m, output_price_per_m,
  is_available,
  provider_metadata
) VALUES (
  'vllm',
  'Qwen/Qwen3-30B-A3B',
  'Qwen3 30B A3B (vLLM)',
  'qwen-3',
  true, false, false, true, false,
  32768, 8192,
  0, 0,
  false,
  '{"notes": "Self-hosted vLLM inference via Alquist Insight. OpenAI-compatible API on port 8100."}'::jsonb
) ON CONFLICT DO NOTHING;

-- ----------------------------------------------------------------------------
-- RAG brick 1a: embedding models as first-class capability-available entities, so
-- resolveRagBackend('rag.embedding') returns a real embedding model (is_embedding) and
-- the brick-1 sweep can enumerate candidates WHERE is_embedding — capability-derived,
-- NOT an allow-list. Each maps to a corpus vector space: v1 → knowledge_embeddings.embedding
-- vector(1024); v2 → embedding_v2 halfvec(2560). Availability is still gated by the
-- provider's is_enabled (operator opt-in) — openai is enabled-by-default, vllm-local is not.
-- The exact v2 model id is the operator-deployed Qwen3-Embedding variant; this is the
-- intended 2560-dim candidate (idempotent DO NOTHING preserves operator edits).
-- ----------------------------------------------------------------------------
INSERT INTO public.ai_model_registry (
  provider, model_id, display_name, model_family,
  is_chat_capable, is_embedding, embedding_dimensions,
  context_window,
  input_price_per_m, output_price_per_m,
  is_available,
  provider_metadata
) VALUES
  -- Instanční embedder v1: model, který svc-model obsluhuje sám (EMBED_ALIAS).
  -- Jméno NESE SIGNÁL: modelDiscovery odvozuje is_embedding z podřetězce v id
  -- (NON_CHAT_MODEL_MARKERS), takže alias bez „embedding" by se zaregistroval
  -- jako CHAT model. Korpus se tímhle modelem embeduje LOKÁLNĚ (v ingestu, MLX;
  -- na serveru llama.cpp) — proto je v1 prostor 1024, ne 1536.
  -- TÝŽ prostor, JINÝ build. Korpus embeduje local-ingest na Apple Silicon
  -- (MLX fp16), server obsluhuje GGUF pod aliasem výš. `insert_knowledge_embedding`
  -- páruje na PŘESNÝ model_id, takže poznámka o sdíleném prostoru u řádku níž
  -- sama nestačila: bez vlastního řádku driver každý vektor z bundlu odmítl
  -- („is not a registered is_embedding model"), a produkce měla 0 embeddingů
  -- při 22 905 hotových vektorech v balíčku (naměřeno 2026-07-31).
  --
  -- Registruje se jako SAMOSTATNÝ řádek, ne přejmenováním: vektor má nést, čím
  -- byl doopravdy spočítán. Vydávat MLX fp16 za vllm build by byla nepravda
  -- v provenienci kvůli průchodu bránou.
  -- is_available = FALSE, a je to POCTIVÉ, ne opatrnost: MLX běží jen na Apple
  -- Silicon, produkční hostitel je x86 Linux — tenhle build tam spustit NELZE. Zápis vektorů
  -- to nepotřebuje (`insert_knowledge_embedding` hledá jen `model_id` +
  -- `is_embedding`), kdežto routování ano (`fn_resolve_embedding_model` chce
  -- `is_available` A enabled providera). Řádek tedy říká „tenhle model znám a
  -- jeho vektory beru", ne „umím ho zavolat".
  ('mlx', 'mlx-community/bge-m3-mlx-fp16', 'BGE-M3 MLX fp16 (RAG v1, 1024, korpusový embedder ingestu, NEspustitelný na serveru)', 'bge-m3',
   false, true, 1024, 8192, 0, 0, false,
   '{"notes": "Korpusový embedder local-ingestu na Apple Silicon. TÝŽ prostor jako bge-m3-embedding (v1, 1024) — jiný build téhož modelu, proto vlastní řádek: insert_knowledge_embedding páruje na přesný model_id a provenience má říkat pravdu o tom, co vektor spočítalo.", "rag_space": "v1"}'::jsonb),
  -- is_available = FALSE, dokud ho discovery neuvidí v živém listingu svc-model
  -- (a nezměří jeho skutečný rozměr — 1024 je tu deklarace k aliasu, který volí instance).
  ('vllm', 'bge-m3-embedding', 'BGE-M3 (RAG v1, 1024, multilingual, instanční)', 'bge-m3',
   false, true, 1024, 8192, 0, 0, false,
   '{"notes": "RAG v1 corpus space — knowledge_embeddings.embedding vector(1024). Self-hosted, OpenAI-compatible /v1/embeddings. Týž model embeduje korpus v local-ingest (mlx-community/bge-m3-mlx-fp16), takže vektory z bundlu a dotaz z platformy sdílí prostor.", "rag_space": "v1"}'::jsonb),
  -- OpenAI zůstává registrované, ale do ŽÁDNÉHO zdejšího prostoru nepatří:
  -- 1536 ≠ 1024 ani 2560, takže fn_resolve_embedding_model vrátí rag_space NULL.
  -- Není to opomenutí — korpus (interní smlouvy) nemá opouštět instanci, a mlčky
  -- zvolený cizí prostor by to udělal bez jediného rozhodnutí.
  ('openai', 'text-embedding-3-small', 'OpenAI text-embedding-3-small (mimo zdejší prostory, 1536)', 'openai-embed',
   false, true, 1536, 8191, 0.02, 0, true,
   '{"notes": "1536 nemapuje na žádný zdejší korpusový prostor (v1=1024, v2=2560) → rag_space NULL. Ponecháno registrované kvůli historickým řádkům a pro instance, které si v1 prostor postaví na 1536.", "rag_space": null}'::jsonb),
  -- is_available = FALSE — týž důvod jako u řádků výš: dostupnost určuje živý listing.
  ('vllm', 'Qwen/Qwen3-Embedding-4B', 'Qwen3-Embedding-4B (RAG v2, 2560, multilingual)', 'qwen-3-embed',
   false, true, 2560, 32768, 0, 0, false,
   '{"notes": "RAG v2 multilingual corpus space — knowledge_embeddings.embedding_v2 halfvec(2560). Self-hosted vLLM, OpenAI-compatible /v1/embeddings, MRL native 2560. Confirm exact deployed model id.", "rag_space": "v2"}'::jsonb)
ON CONFLICT (provider, model_id) DO NOTHING;

-- ----------------------------------------------------------------------------
-- Link every model to its provider registry row so the capability resolvers
-- (aisha_resolve_clow_backend / get_adaptive_model_tiers) can JOIN on
-- provider_registry_id. A model's `provider` is the family key; the registry
-- `slug` is the addressable provider id — they differ for google/vllm. Without
-- this backfill the JOIN's `r.provider = p.slug` arm silently drops Gemini/vLLM
-- models, so a Gemini- or vLLM-only stack would resolve to nothing. Idempotent.
-- ----------------------------------------------------------------------------
UPDATE public.ai_model_registry r
SET provider_registry_id = p.id
FROM public.ai_provider_registry p
WHERE r.provider_registry_id IS NULL
  AND p.slug = CASE r.provider
                 WHEN 'google' THEN 'google-genai'
                 WHEN 'vllm'   THEN 'vllm-local'
                 ELSE r.provider
               END;

-- ============================================================================
-- agent_tools (6 tools from archived migrations)
-- ============================================================================
INSERT INTO public.agent_tools (name, display_name_key, description, parameters_schema, handler_type, handler_ref, access_tier_min, requires_consent, audit_action) VALUES
  (
    'search_knowledge_base',
    'admin.tools.searchKnowledgeBase',
    'Search the AISHA knowledge base for relevant health, longevity and wellness topics.',
    '{"type":"object","properties":{"query":{"type":"string","description":"Search query in natural language"},"limit":{"type":"integer","description":"Max results to return","default":5}},"required":["query"]}',
    'rpc',
    'get_knowledge_topics_localized',
    'basic',
    false,
    NULL
  ),
  (
    'get_my_lab_results',
    'admin.tools.getMyLabResults',
    'Retrieve the authenticated user''s laboratory test results.',
    '{"type":"object","properties":{"limit":{"type":"integer","description":"Max results","default":10}},"required":[]}',
    'rpc',
    'get_my_lab_results_audited',
    'health_data',
    true,
    'HEALTH_DATA_READ'
  ),
  (
    'get_longevity_score',
    'admin.tools.getLongevityScore',
    'Get the user''s current longevity score including trend data, weak areas and improvement suggestions.',
    '{"type":"object","properties":{},"required":[]}',
    'rpc',
    'get_longevity_score_audited',
    'health_data',
    true,
    'HEALTH_DATA_READ'
  ),
  (
    'get_study_info',
    'admin.tools.getStudyInfo',
    'Get detailed information about a specific study/program.',
    '{"type":"object","properties":{"study_id":{"type":"string","format":"uuid","description":"UUID of the study"}},"required":["study_id"]}',
    'rpc',
    'get_study_detail',
    'basic',
    false,
    NULL
  ),
  (
    'create_reminder',
    'admin.tools.createReminder',
    'Create a reminder for the user within their current story/project.',
    '{"type":"object","properties":{"title":{"type":"string","description":"Reminder title"},"remind_at":{"type":"string","format":"date-time","description":"When to remind (ISO 8601)"}},"required":["title","remind_at"]}',
    'rpc',
    'create_story_reminder_audited',
    'basic',
    false,
    'REMINDER_CREATED'
  ),
  (
    'get_dosage_plan',
    'admin.tools.getDosagePlan',
    'Retrieve the user''s current distribution plans: what to take/do, how much, how often, with adherence target. Supplements/medication are one instantiation; the underlying model (distribution_protocols + member_distribution_plans) is domain-neutral.',
    '{"type":"object","properties":{},"required":[]}',
    'rpc',
    -- handler_ref follows the ABSTRACTION, not the pre-transposition name. The
    -- dosage_* model was generalised to distribution_* (dosage_protocols ->
    -- distribution_protocols, member_dosage_plans -> member_distribution_plans)
    -- and the function came with it as get_my_distribution_plans() — same TABLE
    -- contract, verbatim. The old name get_my_dosage_plans() exists in NO
    -- schema, so this tool resolved to nothing on every instance.
    'get_my_distribution_plans',
    'health_data',
    true,
    'HEALTH_DATA_READ'
  )
ON CONFLICT (name) DO NOTHING;

-- ============================================================================
-- agent_tool_bindings — REMOVED
-- Table agent_tool_bindings was dropped by migration
-- 20260411180000_drop_agent_configurations.sql (channel-centric architecture).
-- ============================================================================

-- ============================================================================
-- ai_workflow_definitions (2 pipelines from archived migrations)
-- ============================================================================
INSERT INTO public.ai_workflow_definitions (name, display_name, description, context, is_active, version, graph)
VALUES (
  'default_chat_pipeline',
  'Default Chat Pipeline',
  'Standard classify -> specialist -> main_agent -> simplicity pipeline with parallel fan-out support and optional critic.',
  'chat',
  true,
  1,
  '{
    "entry": "classify",
    "nodes": {
      "classify": {
        "type": "classifier",
        "agent": "classify",
        "description": "Classify user message into routing category",
        "transitions": { "__default__": "specialist", "Else": "main_agent" }
      },
      "specialist": {
        "type": "agent",
        "agent": "__from_category__",
        "description": "Get specialist context based on classification",
        "next": "main_agent",
        "config": { "inject_as": "developer_context", "max_history": 10 }
      },
      "main_agent": {
        "type": "agent",
        "agent": "main_agent",
        "description": "Generate final response with full context",
        "next": "simplicity",
        "config": { "enable_tools": true, "max_tool_iterations": 5, "max_history": 20 }
      },
      "simplicity": {
        "type": "agent",
        "agent": "simplicity",
        "description": "Simplify response for readability",
        "next": null,
        "config": { "condition": "guardrails.useSimplicityAgent && content.length > 200", "fallthrough": true }
      }
    }
  }'::jsonb
)
ON CONFLICT (name) DO UPDATE
SET graph = EXCLUDED.graph, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    version = ai_workflow_definitions.version + 1, updated_at = now();

INSERT INTO public.ai_workflow_definitions (name, display_name, description, context, is_active, version, graph)
VALUES (
  'parallel_multi_specialist',
  'Parallel Multi-Specialist Pipeline',
  'Classifier can route to multiple specialists in parallel. Results are merged before main_agent.',
  'chat',
  false,
  1,
  '{
    "entry": "classify",
    "nodes": {
      "classify": {
        "type": "classifier",
        "agent": "classify",
        "description": "Classify user message — may return multiple categories",
        "transitions": { "__default__": "specialist_fanout", "Else": "main_agent" },
        "config": { "multi_category": true, "max_categories": 3 }
      },
      "specialist_fanout": {
        "type": "parallel",
        "description": "Fan-out to multiple specialists based on categories",
        "children": "__from_categories__",
        "merge_strategy": "concatenate",
        "next": "main_agent",
        "config": { "timeout_ms": 15000, "inject_as": "developer_context" }
      },
      "main_agent": {
        "type": "agent",
        "agent": "main_agent",
        "description": "Generate final response with merged specialist context",
        "next": "critic",
        "config": { "enable_tools": true, "max_tool_iterations": 5 }
      },
      "critic": {
        "type": "critic",
        "agent": "__evaluator__",
        "description": "Review and optionally re-generate response",
        "target_node": "main_agent",
        "next": "simplicity",
        "config": { "max_iterations": 2, "threshold": 0.7, "model": "gpt-4o-mini" }
      },
      "simplicity": {
        "type": "agent",
        "agent": "simplicity",
        "description": "Simplify response for readability",
        "next": null,
        "config": { "condition": "guardrails.useSimplicityAgent && content.length > 200", "fallthrough": true }
      }
    }
  }'::jsonb
)
ON CONFLICT (name) DO UPDATE
SET graph = EXCLUDED.graph, display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    version = ai_workflow_definitions.version + 1, updated_at = now();

-- ============================================================================
-- agent_decision_trees (3 trees from archived migrations — refs agent_catalog)
-- ============================================================================

-- Task Routing Decision Tree (for dirigent agent)
INSERT INTO public.agent_decision_trees (
  agent_id, tree_name, display_name, description, trigger_context, tree_definition
)
SELECT
  ac.id,
  'task_routing',
  'Task Routing Decision Tree',
  'Routes incoming tasks to the appropriate specialist agent based on task category and risk level',
  'routing',
  jsonb_build_object(
    'version', 1,
    'root', 'classify_task',
    'nodes', jsonb_build_array(
      jsonb_build_object('id', 'classify_task', 'type', 'condition', 'description', 'Classify the incoming task by category', 'field', 'task.category',
        'branches', jsonb_build_array(
          jsonb_build_object('value', 'code_review', 'next', 'route_dev_patch'),
          jsonb_build_object('value', 'security', 'next', 'route_compliance'),
          jsonb_build_object('value', 'knowledge', 'next', 'route_librarian'),
          jsonb_build_object('value', 'verification', 'next', 'route_verifier'),
          jsonb_build_object('value', 'planning', 'next', 'route_planner'),
          jsonb_build_object('value', 'debugging', 'next', 'route_debug'),
          jsonb_build_object('value', 'default', 'next', 'assess_risk')
        )),
      jsonb_build_object('id', 'assess_risk', 'type', 'condition', 'description', 'Assess risk level', 'field', 'task.risk_level',
        'branches', jsonb_build_array(
          jsonb_build_object('value', 'high', 'next', 'escalate_human'),
          jsonb_build_object('value', 'medium', 'next', 'route_compliance'),
          jsonb_build_object('value', 'low', 'next', 'route_dev_patch')
        )),
      jsonb_build_object('id', 'route_dev_patch', 'type', 'action', 'agent_slug', 'dev_patch'),
      jsonb_build_object('id', 'route_compliance', 'type', 'action', 'agent_slug', 'compliance_gate'),
      jsonb_build_object('id', 'route_librarian', 'type', 'action', 'agent_slug', 'librarian'),
      jsonb_build_object('id', 'route_verifier', 'type', 'action', 'agent_slug', 'verifier'),
      jsonb_build_object('id', 'route_planner', 'type', 'action', 'agent_slug', 'dirigent'),
      jsonb_build_object('id', 'route_debug', 'type', 'action', 'agent_slug', 'debug_agent'),
      jsonb_build_object('id', 'escalate_human', 'type', 'escalation', 'reason', 'High risk task requires human approval')
    )
  )
FROM public.agent_catalog ac WHERE ac.slug = 'dirigent'
AND NOT EXISTS (
  SELECT 1 FROM public.agent_decision_trees adt WHERE adt.agent_id = ac.id AND adt.tree_name = 'task_routing'
);

-- Risk Assessment Decision Tree (for compliance_gate agent)
INSERT INTO public.agent_decision_trees (
  agent_id, tree_name, display_name, description, trigger_context, tree_definition
)
SELECT
  ac.id,
  'risk_assessment',
  'Risk Assessment Decision Tree',
  'Evaluates compliance risk and determines approval path',
  'compliance',
  jsonb_build_object(
    'version', 1,
    'root', 'check_sensitivity',
    'nodes', jsonb_build_array(
      jsonb_build_object('id', 'check_sensitivity', 'type', 'condition', 'description', 'Check data sensitivity', 'field', 'request.data_sensitivity',
        'branches', jsonb_build_array(
          jsonb_build_object('value', 'sensitive', 'next', 'require_human'),
          jsonb_build_object('value', 'internal', 'next', 'check_scope'),
          jsonb_build_object('value', 'public', 'next', 'auto_approve')
        )),
      jsonb_build_object('id', 'check_scope', 'type', 'condition', 'description', 'Check scope of changes', 'field', 'request.change_scope',
        'branches', jsonb_build_array(
          jsonb_build_object('value', 'schema_change', 'next', 'require_human'),
          jsonb_build_object('value', 'data_mutation', 'next', 'require_review'),
          jsonb_build_object('value', 'read_only', 'next', 'auto_approve')
        )),
      jsonb_build_object('id', 'auto_approve', 'type', 'action', 'decision', 'approved', 'reason', 'Low risk, auto-approved'),
      jsonb_build_object('id', 'require_review', 'type', 'action', 'decision', 'review', 'reason', 'Medium risk, requires compliance review'),
      jsonb_build_object('id', 'require_human', 'type', 'escalation', 'decision', 'escalated', 'reason', 'High sensitivity requires human approval')
    )
  )
FROM public.agent_catalog ac WHERE ac.slug = 'compliance_gate'
AND NOT EXISTS (
  SELECT 1 FROM public.agent_decision_trees adt WHERE adt.agent_id = ac.id AND adt.tree_name = 'risk_assessment'
);

-- SDLC Analysis Phase Gate (for dirigent agent)
INSERT INTO public.agent_decision_trees (
  agent_id, tree_name, display_name, description, tree_definition, trigger_context, is_active, version, created_by
)
SELECT
  ac.id,
  'sdlc_analysis_gate',
  'SDLC Analysis Phase Gate',
  'Validates that a story cannot leave the analyzing phase without confirmed technical analysis and stakeholder agreement.',
  '{
    "version": 1,
    "root": "check_delivery_status",
    "nodes": [
      {"id": "check_delivery_status", "type": "condition", "field": "story.delivery_status",
       "branches": [{"value": "analyzing", "next": "check_analysis_exists"}, {"value": "default", "next": "approve_non_analyzing"}]},
      {"id": "check_analysis_exists", "type": "condition", "field": "story.has_technical_analysis",
       "branches": [{"value": "true", "next": "check_stakeholder_agreement"}, {"value": "false", "next": "block_no_analysis"}]},
      {"id": "check_stakeholder_agreement", "type": "condition", "field": "story.stakeholder_agreed",
       "branches": [{"value": "true", "next": "approve_transition"}, {"value": "false", "next": "block_no_agreement"}]},
      {"id": "approve_transition", "type": "action", "decision": "approved", "message": "Analysis confirmed, stakeholder agreed."},
      {"id": "approve_non_analyzing", "type": "action", "decision": "approved", "message": "Story not in analyzing phase. Gate does not apply."},
      {"id": "block_no_analysis", "type": "escalation", "reason": "Cannot leave analyzing: no technical analysis found."},
      {"id": "block_no_agreement", "type": "escalation", "reason": "Cannot leave analyzing: stakeholder has not confirmed agreement."}
    ]
  }'::jsonb,
  'sdlc',
  true,
  1,
  NULL
FROM public.agent_catalog ac WHERE ac.slug = 'dirigent'
AND NOT EXISTS (
  SELECT 1 FROM public.agent_decision_trees adt WHERE adt.agent_id = ac.id AND adt.tree_name = 'sdlc_analysis_gate'
);

-- ============================================================================
-- Step 7.3 follow-up: enable the graph_context retrieval layer on RAG profiles.
-- Inserts 'graph_context' right after 'kb_retrieval' in priority_order and merges
-- the layer config. Idempotent (skips profiles already wired). Keeps fresh-DB seed
-- in parity with migration *_compose_context_graph_layer.sql.
-- ============================================================================
-- depth/per_seed now live on the typed columns (graph_depth/graph_per_seed), the
-- single SoT read by BOTH compose_context (retrieval) and fn_get_run_graph_context
-- (panel). The graph_context JSONB keeps only layer-presentation config (enabled,
-- max_edges). graph_per_seed=8 preserves the prior retrieval per_seed (was JSONB 8,
-- panel column-default 10 — now unified at 8).
UPDATE public.context_profiles cp
SET
  layers = cp.layers || jsonb_build_object(
    'graph_context',
    jsonb_build_object('enabled', true, 'max_edges', 20)
  ),
  graph_per_seed = 8,
  priority_order = (
    SELECT array_agg(elem ORDER BY ord)
    FROM (
      SELECT t.elem, t.ord::numeric AS ord
      FROM unnest(cp.priority_order) WITH ORDINALITY AS t(elem, ord)
      UNION ALL
      SELECT 'graph_context', t.ord + 0.5
      FROM unnest(cp.priority_order) WITH ORDINALITY AS t(elem, ord)
      WHERE t.elem = 'kb_retrieval'
    ) merged
  )
WHERE COALESCE((cp.layers->'kb_retrieval'->>'enabled')::boolean, false) = true
  AND cp.slug <> 'chat_lightweight'  -- lightweight profile stays lean: no graph layer
  AND NOT (cp.priority_order @> ARRAY['graph_context']);

-- Per-profile graph reasoning budget on the typed column. evidence_strict runs
-- deep/deliberative retrieval → deeper multi-hop traversal than the default 2.
-- Idempotent; honored identically by compose_context and the explainability panel.
UPDATE public.context_profiles SET graph_depth = 3 WHERE slug = 'evidence_strict';
