-- ==============================================================================
-- Reflection graph workflow definitions
-- GENERATED by scripts/db/gen-reflection-graph-seed.mjs — DO NOT EDIT BY HAND.
-- Source of truth: services/svc-ai-chat/src/reflection/graphs/*.json
-- Regenerate:      npm run db:seed:reflection-graphs
--
-- Why this exists: the reflection orchestrator loads its graph from
-- ai_workflow_definitions by name (aisha_choose_execution_strategy resolves
-- task_type -> graph name). Without these rows a reflection / Tree-of-Thoughts
-- run fails at load with "Workflow definition not found".
-- ==============================================================================

-- source: services/svc-ai-chat/src/reflection/graphs/deploy-reflect.json
INSERT INTO public.ai_workflow_definitions
  (name, display_name, description, context, is_active, version, metadata, graph)
VALUES (
  'deploy-reflect',
  'Deploy Reflection (AISHA self-use)',
  'Pilot graph for AISHA''s own deployment reflection. Generator proposes deploy plan, critic evaluates compliance/risk/completeness, convergence_gate loops until threshold or max_iterations, openclaw_sandbox dry-runs the plan, interrupt awaits human approval for sandbox warnings, cosmos_anchor records the final decision, hippocampus_write captures the learning.',
  'reflection',
  true,
  1,
  '{"mode":"strict","pilot":true,"owner":"platform"}'::jsonb,
  '{"entry":"soulforge_classify","nodes":[{"id":"soulforge_classify","type":"soulforge_classify","config":{}},{"id":"soulforge_optimize","type":"soulforge_optimize","config":{"max_history_chars":6000}},{"id":"hippocampus_read","type":"hippocampus_read","config":{"limit":5,"min_importance":3}},{"id":"openclaw_plan","type":"openclaw_plan","config":{"task_type":"deploy"}},{"id":"generator","type":"generator","config":{"slot":"ember","temperature":0.3}},{"id":"critic","type":"critic","config":{"rules":["compliance","risk","completeness"],"slot":"verify"}},{"id":"convergence_gate","type":"convergence_gate","config":{"min_score":0.85,"max_iterations":3}},{"id":"corrector","type":"corrector","config":{"slot":"ember"}},{"id":"openclaw_sandbox","type":"openclaw_sandbox","config":{"timeout_s":120}},{"id":"interrupt","type":"interrupt","config":{"channel":"telegram","approver":"dirigent","reason":"sandbox_warnings"}},{"id":"cosmos_anchor","type":"cosmos_anchor","config":{}},{"id":"hippocampus_write","type":"hippocampus_write","config":{"importance":"critic_score"}}],"edges":[{"from":"soulforge_classify","to":"soulforge_optimize"},{"from":"soulforge_optimize","to":"hippocampus_read"},{"from":"hippocampus_read","to":"openclaw_plan"},{"from":"openclaw_plan","to":"generator"},{"from":"generator","to":"critic"},{"from":"critic","to":"convergence_gate"},{"from":"convergence_gate","to":"corrector","condition":"convergence_result == ''retry''"},{"from":"convergence_gate","to":"openclaw_sandbox","condition":"convergence_result == ''pass''"},{"from":"convergence_gate","to":"hippocampus_write","condition":"convergence_result == ''exhausted''"},{"from":"corrector","to":"generator"},{"from":"openclaw_sandbox","to":"interrupt","condition":"warnings.length > 0"},{"from":"openclaw_sandbox","to":"cosmos_anchor","condition":"warnings.length == 0"},{"from":"interrupt","to":"cosmos_anchor","condition":"approved == true"},{"from":"cosmos_anchor","to":"hippocampus_write"}]}'::jsonb
)
ON CONFLICT (name) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description  = EXCLUDED.description,
  context      = EXCLUDED.context,
  is_active    = EXCLUDED.is_active,
  metadata     = EXCLUDED.metadata,
  graph        = EXCLUDED.graph,
  version      = ai_workflow_definitions.version + 1,
  updated_at   = now();

-- source: services/svc-ai-chat/src/reflection/graphs/reasoning-tree-reflect.json
INSERT INTO public.ai_workflow_definitions
  (name, display_name, description, context, is_active, version, metadata, graph)
VALUES (
  'reasoning-tree-reflect',
  'Reasoning Tree (single-run Tree-of-Thoughts)',
  'E1 single-run Tree-of-Thoughts deliberation. tot_planner seeds the root + sizes the wave by REUSING the #443 deliberation kernel (planDeliberation), tot_expand fans out wave_width journaled drafters, tot_evaluate scores them Sure/Maybe/Impossible (critic-style 0..1), tot_search holds all BFS/DFS/beam + budget policy and loops back to expand or terminates. node_type is free text and the graph is JSONB, so this is pure wire-up — no DB migration. Edges read ONLY the flat tot_action/tot_done fields the guarded edge grammar supports.',
  'reflection',
  true,
  1,
  '{"mode":"deliberation","pilot":true,"owner":"platform","phase":"E1.2"}'::jsonb,
  '{"entry":"tot_planner","max_iterations":40,"nodes":[{"id":"tot_planner","type":"tot_planner","config":{}},{"id":"tot_expand","type":"tot_expand","config":{"slot":"semantic","temperature":0.7,"max_tokens":512}},{"id":"tot_evaluate","type":"tot_evaluate","config":{"slot":"verify","max_tokens":1024}},{"id":"tot_search","type":"tot_search","config":{}}],"edges":[{"from":"tot_planner","to":"tot_expand"},{"from":"tot_expand","to":"tot_evaluate"},{"from":"tot_evaluate","to":"tot_search"},{"from":"tot_search","to":"tot_expand","condition":"tot_action == ''expand''"}]}'::jsonb
)
ON CONFLICT (name) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description  = EXCLUDED.description,
  context      = EXCLUDED.context,
  is_active    = EXCLUDED.is_active,
  metadata     = EXCLUDED.metadata,
  graph        = EXCLUDED.graph,
  version      = ai_workflow_definitions.version + 1,
  updated_at   = now();

-- source: services/svc-ai-chat/src/reflection/graphs/runtime-execute.json
INSERT INTO public.ai_workflow_definitions
  (name, display_name, description, context, is_active, version, metadata, graph)
VALUES (
  'runtime-execute',
  'Runtime Execute (derive runtime + dispatch)',
  'E3 executor pipeline. resolve_clow (openclaw_resolve_clow) DERIVES the executor runtime via fn_resolve_runtime (direct_llm/openclaw/hermes — capability-availability, no hardcoded default), admits the clow (fn_admit_clow, fail-loud), and resolves the model (aisha_resolve_clow_backend, serviceable-filtered). dispatch (runtime_dispatch) then EXECUTES the work through the derived RuntimeAdapter and journals it (ai_decisions). node_type is free text and the graph is JSONB, so this is pure wire-up over registered nodes — no DB migration.',
  'reflection',
  true,
  1,
  '{"mode":"execute","owner":"platform","phase":"E3"}'::jsonb,
  '{"entry":"resolve_clow","max_iterations":4,"nodes":[{"id":"resolve_clow","type":"openclaw_resolve_clow","config":{"soft_fail":false}},{"id":"dispatch","type":"runtime_dispatch","config":{}}],"edges":[{"from":"resolve_clow","to":"dispatch","condition":"admission_verdict == ''allow''"}]}'::jsonb
)
ON CONFLICT (name) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description  = EXCLUDED.description,
  context      = EXCLUDED.context,
  is_active    = EXCLUDED.is_active,
  metadata     = EXCLUDED.metadata,
  graph        = EXCLUDED.graph,
  version      = ai_workflow_definitions.version + 1,
  updated_at   = now();

-- source: services/svc-ai-chat/src/reflection/graphs/story-plan-reflect.json
INSERT INTO public.ai_workflow_definitions
  (name, display_name, description, context, is_active, version, metadata, graph)
VALUES (
  'story-plan-reflect',
  'Story Plan Reflection (partner product)',
  'Phase 2 product graph for partner story planning. Generator runs with creative_with_dna context profile (Psyché DNA injection), occipitum_creative produces parallel creative branch, critic evaluates brand_voice + compliance + feasibility, convergence threshold 0.80 (creative work tolerates more deviation), interrupt routes to partner-configured channel.',
  'reflection',
  true,
  1,
  '{"mode":"creative","pilot":false,"owner":"partner_facing"}'::jsonb,
  '{"entry":"soulforge_classify","nodes":[{"id":"soulforge_classify","type":"soulforge_classify","config":{}},{"id":"soulforge_optimize","type":"soulforge_optimize","config":{"max_history_chars":10000}},{"id":"hippocampus_read","type":"hippocampus_read","config":{"limit":5,"min_importance":3}},{"id":"generator","type":"generator","config":{"slot":"semantic","temperature":0.5}},{"id":"occipitum_creative","type":"occipitum_creative","config":{"slot":"semantic","temperature":0.85,"profile":"maxQuality"}},{"id":"critic","type":"critic","config":{"rules":["brand_voice","compliance","feasibility"],"slot":"verify","threshold":0.8}},{"id":"convergence_gate","type":"convergence_gate","config":{"min_score":0.8,"max_iterations":3}},{"id":"corrector","type":"corrector","config":{"slot":"semantic"}},{"id":"interrupt","type":"interrupt","config":{"channel":"in_app","approver":"partner","reason":"partner_review"}},{"id":"hippocampus_write","type":"hippocampus_write","config":{"importance":"critic_score"}}],"edges":[{"from":"soulforge_classify","to":"soulforge_optimize"},{"from":"soulforge_optimize","to":"hippocampus_read"},{"from":"hippocampus_read","to":"generator"},{"from":"generator","to":"occipitum_creative"},{"from":"occipitum_creative","to":"critic"},{"from":"critic","to":"convergence_gate"},{"from":"convergence_gate","to":"corrector","condition":"convergence_result == ''retry''"},{"from":"convergence_gate","to":"interrupt","condition":"convergence_result == ''pass''"},{"from":"convergence_gate","to":"hippocampus_write","condition":"convergence_result == ''exhausted''"},{"from":"corrector","to":"generator"},{"from":"interrupt","to":"hippocampus_write","condition":"approved == true"}]}'::jsonb
)
ON CONFLICT (name) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description  = EXCLUDED.description,
  context      = EXCLUDED.context,
  is_active    = EXCLUDED.is_active,
  metadata     = EXCLUDED.metadata,
  graph        = EXCLUDED.graph,
  version      = ai_workflow_definitions.version + 1,
  updated_at   = now();
