/**
 * PageRenderer — Renders GrapeJS canvas HTML with i18n key resolution
 * and runtime block hydration.
 *
 * Takes canvas_html and canvas_css from a web_page record and:
 * 1. Extracts all `data-i18n-key` attributes from the HTML
 * 2. Resolves them via useDynamicTranslationsMap (DB translations)
 * 3. Falls back to react-i18next static keys for unresolved ones
 * 4. Splits HTML at `data-runtime-block` placeholders
 * 5. Sanitizes static segments via DOMPurify
 * 6. Delegates runtime blocks to RuntimeBlockRenderer
 * 7. Injects scoped CSS
 *
 * @module
 */

import { useEffect, useMemo } from "react";
import DOMPurify from "dompurify";
// ⛔ JEDINÝ DOMOV TRANSFORMACE. Tyhle funkce tu dřív žily lokálně — jenže
// tutéž logiku měl i svc-web-artifact (i18nKeyExtractor.ts) a při stavbě
// generátoru statických stránek by vznikla TŘETÍ kopie. Rozdíl mezi nimi
// by znamenal, že stránka vypadá jinak podle toho, jak na ni návštěvník
// přišel — přímým načtením vs. proklikem. Sjednoceno 2026-08-30.
import {
  SANITIZE_OPTS,
  extractI18nKeys as sdileneExtractI18nKeys,
  expandPartials as sdileneExpandPartials,
  hasPartials as sdileneHasPartials,
  resolveI18nInHtml as sdileneResolveI18nInHtml,
} from "@aisha/web-canvas";
import { useLayoutEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { useTranslation } from "react-i18next";
import { useDynamicTranslationsMap } from "@/hooks/useDynamicTranslations";
import { RuntimeBlockRenderer } from "./RuntimeBlockRenderer";
import { useWebPartials } from "@/hooks/useWebPartials";
import { scopeCanvasCss } from "./scopeCanvasCss";
import { safeError, safeWarn } from "@/lib/security/safeLogger";
import {
  WEB_I18N_ATTRIBUTE_BINDINGS,
  WEB_TEXT_I18N_KEY_ATTRS,
} from "@/lib/builder/webI18nBindings";

// Side-effect import: registers all runtime blocks in the registry
import "@/lib/builder/runtimeBlockRegistry";

import type { RuntimeBlockConfig } from "@/lib/builder/runtimeBlockRegistry";

// =====================================================
// Types
// =====================================================

interface PageRendererProps {
  /** The CSS generated by GrapesJS */
  canvasCss: string | null;
  /** The HTML generated by GrapesJS */
  canvasHtml: string | null;
  /** Page-level visual settings from web_pages.page_settings */
  pageSettings?: PageSettings | null;
}

/** Page-level visual settings stored in web_pages.page_settings JSONB */
interface PageSettings {
  /** CSS background (color, gradient, or image) for the page wrapper */
  background?: string;
  /** Additional CSS class names for the page wrapper */
  className?: string;
  /** Inline CSS overrides for the page wrapper */
  style?: Record<string, string>;
}

// =====================================================
// Helpers
// =====================================================

const WEB_I18N_KEY_ATTRS = [
  ...WEB_TEXT_I18N_KEY_ATTRS,
  ...WEB_I18N_ATTRIBUTE_BINDINGS.map((b) => b.keyAttr),
] as const;

const WEB_I18N_SANITIZE_ATTRS = [
  ...WEB_I18N_KEY_ATTRS,
  ...WEB_I18N_ATTRIBUTE_BINDINGS.map((b) => b.targetAttr),
] as const;

const WEB_I18N_SELECTOR = WEB_I18N_KEY_ATTRS
  .map((attr) => `[${attr}]`)
  .join(",");

const I18N_KEY_ATTR_REGEX =
  /\b(?:data-i18n-key|data-i18n|data-i18n-placeholder-key|data-i18n-title-key|data-i18n-aria-label-key|data-i18n-alt-key)=["']([^"']+)["']/g;

/**
 * Regex matching ANY div opening tag, capturing its raw attribute string once.
 * A SINGLE `[^>]*` run → linear-time, unambiguous. (The previous pattern had
 * three `[^>]*` runs straddling an OPTIONAL data-block-config group, which made
 * matching polynomial on adversarial admin-authored canvas HTML.) We then
 * filter for data-runtime-block and pull the two attributes out of the captured
 * string with simple anchored sub-matches below.
 */
const DIV_TAG_REGEX = /<div\b([^>]*)>(?:<\/div>)?/g;
const RUNTIME_BLOCK_ATTR = /\bdata-runtime-block="([^"]+)"/;
const RUNTIME_BLOCK_CONFIG_ATTR = /\bdata-block-config='([^']*)'/;








/**
 * Parse a JSON config string from data-block-config attribute.
 * Returns empty object on invalid/missing JSON.
 *
 * Seed-ingested pages carry the attribute HTML-entity-escaped (the
 * web-artifact serializer emits {&quot;skipHref&quot;:...}) — decode the
 * five basic entities before JSON.parse or every template-seeded block
 * silently loses its config.
 */
function decodeBasicEntities(raw: string): string {
  return raw
    .replace(/&quot;/g, '"')
    .replace(/&#0?39;/g, "'")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&amp;/g, "&");
}



// =====================================================
// DOMPurify config
// =====================================================


/** Parser a sanitizér pro PROHLÍŽEČ — v Node je dodá jsdom. */
const parseHtmlProProhlizec = (html: string): Document =>
  new DOMParser().parseFromString(html, "text/html");
const sanitizeProProhlizec = ((html: string, opts: never) =>
  DOMPurify.sanitize(html, opts)) as never;

// =====================================================
// Component
// =====================================================

/**
 * Renders GrapeJS-generated HTML with i18n resolution, DOMPurify
 * sanitization, and runtime block hydration.
 *
 * Static HTML segments are sanitized (DOMPurify) and injected into the DOM.
 * Runtime block placeholders are replaced with live React components.
 * CSS is scoped under `.gjs-page-content` to avoid Tailwind collisions.
 */
export function PageRenderer({ canvasCss, canvasHtml, pageSettings }: PageRendererProps) {
  const { t } = useTranslation();

  // ⛔ ÚTRŽKY SE DOSAZUJÍ PRVNÍ. Hlavička a patička žijí v `web_pages` jako
  // sdílený obsah (`role: partial`) a do stránky se vkládají značkou
  // `<div data-partial="nav">`. Musí se rozbalit PŘED extrakcí klíčů, protože
  // si nesou vlastní `data-i18n-key` (`web.nav.home`) — jinak by se pro ně
  // překlady nikdy nevyžádaly a navigace by zůstala v původním jazyce.
  const { data: partials, isLoading: partialsLoading } = useWebPartials();

  // ⛔ JEDNA MEMOIZACE, NE DVĚ. Dosazení útržků a extrakce klíčů jsou dva kroky
  // téhož průchodu a závisí na týchž vstupech — rozdělit je do dvou `useMemo`
  // by znamenalo dokument parsovat dvakrát a přidat další ruční memoizaci nad
  // rámec račny (`wp-4-5-react-compiler`), která jejich počet drží dolů.
  // Odebrat memoizaci úplně nelze: React Compiler v tomhle stromu ještě
  // zapnutý NENÍ, takže by se `missing` tvořilo při každém vykreslení a efekt
  // pod tím by se spouštěl donekonečna.
  const zaklad = useMemo(() => {
    if (!canvasHtml) return { html: "", klice: [] as string[], missing: [] as string[] };
    const { html, missing } = sdileneExpandPartials(canvasHtml, partials ?? {});
    return { html, klice: sdileneExtractI18nKeys(html, parseHtmlProProhlizec), missing };
  }, [canvasHtml, partials]);

  const expandedHtml = zaklad.html;
  const i18nKeys = zaklad.klice;

  // Chybějící útržek je vada AUTORA nebo seedu, ne návštěvníka — značka
  // zůstane v HTML jako stopa a tady se to řekne nahlas. Tiché vypuštění by
  // vypadalo jako stránka záměrně bez hlavičky.
  useEffect(() => {
    for (const ref of zaklad.missing) {
      safeWarn(`PageRenderer: útržek "${ref}" neexistuje — zkontroluj page_settings.role='partial'`);
    }
  }, [zaklad.missing]);

  // Resolve keys from DB translations.
  //
  // namespace=null triggers per-key namespace inference (added in DB
  // migration 20260525130000_translations_rpc_namespace_inference): each
  // key's namespace is derived from its first dot-segment, so a single
  // canvas can mix arbitrary namespaces (agents.*, achievements.*, a brand's
  // own prefix …) and they all
  // resolve in one round-trip. The previous hardcoded "web" namespace
  // matched zero seeded rows and silently dropped every key — every
  // tenant's authored content rendered as raw i18n literals on screen.
  //
  // fallbackLocale='en' keeps the existing English-fallback behavior for
  // locales that are only partially translated.
  const translationsMap = useDynamicTranslationsMap(i18nKeys, null, "en");

  // Build resolved HTML with i18n substitutions
  const resolvedHtml = useMemo(() => {
    if (!expandedHtml) return "";
    return sdileneResolveI18nInHtml(
      expandedHtml,
      translationsMap,
      parseHtmlProProhlizec,
      sanitizeProProhlizec,
      t,
    );
  }, [expandedHtml, translationsMap, t]);

  // POZOR: BLOKY SE MONTUJÍ NA MÍSTO, NE VEDLE (naměřeno 2026-09-01 na produkci).
  //
  // Dřív se plátno DĚLILO na úseky (`splitCanvasSegments`) a každý úsek se balil
  // do vlastního `<div>`. Blok tím pádem nikdy neskončil tam, kde je jeho
  // zástupný symbol — vždycky se stal přímým potomkem obalu plátna. Doloženo:
  //
  //     cesta:     SELECT.nav__lang-vyber → LABEL.nav__lang → DIV.gjs-page-content
  //     vHlavicce: false
  //
  // Přepínač jazyků vložený do `<header>` se proto vykreslil POD hlavičkou jako
  // cizí pruh. A co hůř: obsah, který v rodiči následoval PO bloku, se od svého
  // obalu oddělil (tlačítka hlavičky měla rozměr 0x0 a vypadla ven).
  //
  // Nově se HTML vykreslí VCELKU a komponenty se do zástupných `div`ů portálují.
  // Struktura zůstane přesně taková, jakou autor napsal, a je jedno, jak hluboko
  // je blok vnořený nebo co za ním v rodiči následuje.
  const obalRef = useRef<HTMLDivElement>(null);
  const [mistaBloku, setMistaBloku] = useState<
    { el: HTMLElement; blockType: string; config: RuntimeBlockConfig }[]
  >([]);

  useLayoutEffect(() => {
    const obal = obalRef.current;
    if (!obal) {
      setMistaBloku([]);
      return;
    }

    // ⛔ STATICKÁ KOPIE SE ODSTRANÍ TEPRVE TADY — a odstraní se DOOPRAVDY
    // (naměřeno 2026-09-03 na produkci: každá předrenderovaná stránka byla
    // dvakrát pod sebou — #static-page nahoře, hydratovaná kopie pod ním,
    // 2697 px na indexu). Generátor (svc-web-render) sem od začátku
    // spoléhal: „aplikace #static-page odstraní, až vykreslí totéž" — jenže
    // ten kód neexistoval. Slib bez kódu = dvojí stránka.
    //
    // Proč až tady a ne při startu Reactu: dokud plátno není v DOM, je
    // statická kopie jediné, co člověk vidí. Když SPA na stránku nedosáhne
    // (výpadek API, 429), PageRenderer se nepřipojí a statická verze zůstane
    // — což je lepší než prázdný platformní rám.
    document.getElementById("static-page")?.remove();
    const nalezena = Array.from(
      obal.querySelectorAll<HTMLElement>("[data-runtime-block]"),
    ).map((el) => {
      const blockType = el.getAttribute("data-runtime-block") ?? "";
      let config: RuntimeBlockConfig = {};
      const zapis = el.getAttribute("data-block-config");
      if (zapis) {
        try {
          config = JSON.parse(zapis) as RuntimeBlockConfig;
        } catch (err) {
          // Konfigurace z plátna je VSTUP: rozbitý JSON nesmí shodit stránku,
          // ale MUSÍ být vidět — jinak autor marně hledá, proč nastavení
          // nefunguje. Táž zásada jako v `splitCanvasSegments`.
          safeWarn("PageRenderer.blockConfig", { blockType, err: String(err) });
        }
      }
      // Zástupný náhled pro editor (text uvnitř `div`u) se zahodí — za běhu ho
      // nahrazuje komponenta. Bez toho by prosvítal pod portálem.
      el.replaceChildren();
      return { blockType, config, el };
    });
    setMistaBloku(nalezena);
  }, [resolvedHtml]);

  // Scope canvas CSS under .gjs-page-content (see scopeCanvasCss for the
  // :root/html/body → wrapper mapping that makes template tokens cascade to
  // runtime blocks).
  const scopedCss = useMemo(() => scopeCanvasCss(canvasCss), [canvasCss]);

  if (!canvasHtml) {
    return null;
  }

  // ⛔ TICHO MÍSTO STRÁNKY BEZ HLAVIČKY. Dokud útržky nedorazí, neví se, jak
  // má vršek vypadat — vykreslit obsah bez navigace a doplnit ji za okamžik
  // je viditelný přeskok. Týž postup jako u `WebPageShell` s neznámým
  // `page_settings.chrome`: neznámý stav se řeší tichem, ne dosazením.
  if (partialsLoading && sdileneHasPartials(canvasHtml)) {
    return null;
  }

  // Compute page-level wrapper styles from page_settings.
  // `position: relative` is load-bearing: seeded designs are authored as full
  // standalone documents where `body` is the positioning root, so their
  // absolutely-positioned chrome (nav, hero decorations) is `position:absolute`
  // relative to `body`. Rendered here the canvas lives in this wrapper, BELOW the
  // app Header — if the wrapper is `static`, those absolute elements escape to the
  // viewport/ICB and misalign by the Header's height (nav overlaps the intro
  // banner; hero/CTA/stats pile up). Making the wrapper the positioning context
  // (the canvas's effective `body`) re-anchors them so the design lays out exactly
  // as standalone. pageSettings.style may still override.
  const wrapperStyle: React.CSSProperties = { position: "relative" };
  const wrapperClasses = ["gjs-page-content"];

  if (pageSettings?.background) {
    wrapperStyle.background = pageSettings.background;
  }
  if (pageSettings?.className) {
    wrapperClasses.push(pageSettings.className);
  }
  if (pageSettings?.style) {
    Object.assign(wrapperStyle, pageSettings.style);
  }

  const wrapperClassName = wrapperClasses.join(" ");

  return (
    <>
      {scopedCss && (
        <style dangerouslySetInnerHTML={{ __html: DOMPurify.sanitize(scopedCss, { FORCE_BODY: true }) }} />
      )}

      {/*
        JEDNA INJEKCE HTML pro obě situace. Dřív tu byly dvě větve — „rychlá
        cesta" bez bloků a „hybridní" s dělením na úseky. Hybridní větev byla
        právě ta, která rozbíjela strukturu (viz komentář u `mistaBloku`), takže
        rozdíl mezi cestami zmizel: HTML se vždy vloží vcelku a bloky se do něj
        portálují tam, kde jejich zástupný symbol stojí.
      */}
      <div
        ref={obalRef}
        className={wrapperClassName}
        style={wrapperStyle}
        dangerouslySetInnerHTML={{
          __html: DOMPurify.sanitize(resolvedHtml, SANITIZE_OPTS),
        }}
      />

      {/*
        Portály míří do uzlů, které React NESPRAVUJE (vznikly přes
        `dangerouslySetInnerHTML`). Je to bezpečné, protože obsah obalu se mění
        JEN při změně `resolvedHtml` — a tehdy se efekt výš spustí znovu a
        seznam míst se přepočítá. Klíč nese typ i pořadí, aby dva stejné bloky
        na stránce nesplynuly.
      */}
      {mistaBloku.map(({ blockType, config, el }, idx) =>
        blockType
          ? createPortal(
              <RuntimeBlockRenderer blockType={blockType} config={config} />,
              el,
              `block-${blockType}-${idx}`,
            )
          : null,
      )}
    </>
  );
}
