apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group = 'cz.platforma.rizenakonfigurace'
version = '1.0.0'

android {
  namespace 'cz.platforma.rizenakonfigurace'
  compileSdk rootProject.ext.has('compileSdkVersion') ? rootProject.ext.get('compileSdkVersion') : 35
  defaultConfig {
    minSdk rootProject.ext.has('minSdkVersion') ? rootProject.ext.get('minSdkVersion') : 24
  }
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_17
    targetCompatibility JavaVersion.VERSION_17
  }
  kotlinOptions { jvmTarget = '17' }
}

dependencies {
  implementation project(':expo-modules-core')
  implementation "org.jetbrains.kotlin:kotlin-stdlib:${kotlinVersion}"
}
