/**
 * Expo Config Plugin: Configure Sentry Auth for iOS and Android Builds
 *
 * Ensures SENTRY_AUTH_TOKEN is available for source map uploads:
 * - iOS: Writes to .xcode.env.local
 * - Android: Writes to sentry.properties
 */
const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const getSentryAuthToken = (projectRoot) => {
  if (process.env.SENTRY_AUTH_TOKEN) {
    return process.env.SENTRY_AUTH_TOKEN;
  }

  const envLocalPath = path.join(projectRoot, '.env.local');
  if (fs.existsSync(envLocalPath)) {
    const envContent = fs.readFileSync(envLocalPath, 'utf8');
    const match = envContent.match(/^SENTRY_AUTH_TOKEN=(.+)$/m);
    if (match) {
      return match[1].trim();
    }
  }

  return null;
};

const ensureLine = (content, line) => {
  const pattern = new RegExp(`^${line.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}$`, 'm');
  if (pattern.test(content)) {
    return content;
  }

  return `${content.trimEnd()}\n${line}\n`;
};

const configureIOS = (config, sentryAuthToken) => {
  const projectRoot = config.modRequest.projectRoot;
  const xcodeEnvLocalPath = path.join(projectRoot, 'ios', '.xcode.env.local');

  let xcodeEnvContent = '';
  if (fs.existsSync(xcodeEnvLocalPath)) {
    xcodeEnvContent = fs.readFileSync(xcodeEnvLocalPath, 'utf8');
  }

  // A token IS present → in-build Sentry upload (source maps + dSYMs) must be
  // ENABLED. Strip any "disabled" markers a previous token-less prebuild wrote,
  // otherwise a stale SENTRY_DISABLE_AUTO_UPLOAD=true would keep uploads off.
  xcodeEnvContent = xcodeEnvContent
    .replace(/^export SENTRY_DISABLE_AUTO_UPLOAD=.*$/m, '')
    .replace(/^# Sentry upload disabled.*$/m, '')
    .replace(/\n{3,}/g, '\n\n');

  if (xcodeEnvContent.includes('SENTRY_AUTH_TOKEN=')) {
    xcodeEnvContent = xcodeEnvContent.replace(
      /^export SENTRY_AUTH_TOKEN=.*$/m,
      `export SENTRY_AUTH_TOKEN=${sentryAuthToken}`
    );
  } else {
    xcodeEnvContent = xcodeEnvContent.trimEnd();
    xcodeEnvContent += `\n\n# Sentry auth (auto-generated by withSentryAuth)\nexport SENTRY_AUTH_TOKEN=${sentryAuthToken}\n`;
  }

  fs.writeFileSync(xcodeEnvLocalPath, xcodeEnvContent, 'utf8');
  console.log('[withSentryAuth] iOS: SENTRY_AUTH_TOKEN configured');
  return config;
};

const configureIOSWithoutToken = (config) => {
  const projectRoot = config.modRequest.projectRoot;
  const xcodeEnvLocalPath = path.join(projectRoot, 'ios', '.xcode.env.local');

  let xcodeEnvContent = '';
  if (fs.existsSync(xcodeEnvLocalPath)) {
    xcodeEnvContent = fs.readFileSync(xcodeEnvLocalPath, 'utf8');
  }

  xcodeEnvContent = xcodeEnvContent.replace(/^export SENTRY_AUTH_TOKEN=.*$/m, '').trimEnd();
  xcodeEnvContent = ensureLine(xcodeEnvContent, '# Sentry upload disabled (auto-generated by withSentryAuth)');
  xcodeEnvContent = ensureLine(xcodeEnvContent, 'export SENTRY_DISABLE_AUTO_UPLOAD=true');

  fs.writeFileSync(xcodeEnvLocalPath, `${xcodeEnvContent.trimEnd()}\n`, 'utf8');
  console.log('[withSentryAuth] iOS: SENTRY_DISABLE_AUTO_UPLOAD=true configured');
  return config;
};

// Sentry project slug from version.json brand (env override wins, matching app.config).
const resolveSentryProject = (projectRoot) => {
  if (process.env.SENTRY_PROJECT) return process.env.SENTRY_PROJECT;
  try {
    const v = JSON.parse(fs.readFileSync(path.join(projectRoot, 'version.json'), 'utf8'));
    if (v.brand && v.brand.sentry && v.brand.sentry.project) return v.brand.sentry.project;
  } catch {
    // fall through to default
  }
  return 'aisha-dirigent';
};

const configureAndroid = (config, sentryAuthToken) => {
  const projectRoot = config.modRequest.projectRoot;
  const sentryPropertiesPath = path.join(projectRoot, 'android', 'sentry.properties');
  const sentryProject = resolveSentryProject(projectRoot);

  let content = '';
  if (fs.existsSync(sentryPropertiesPath)) {
    content = fs.readFileSync(sentryPropertiesPath, 'utf8');
  }

  content = content
    .replace(/^defaults\.project=.*$/m, `defaults.project=${sentryProject}`)
    .replace(/^auth\.token=.*$/m, '')
    .replace(/^# Using SENTRY_AUTH_TOKEN.*$/m, '')
    .trimEnd();

  content += `\n\n# Auth token (auto-generated by withSentryAuth)\nauth.token=${sentryAuthToken}\n`;

  fs.writeFileSync(sentryPropertiesPath, content, 'utf8');
  console.log('[withSentryAuth] Android: sentry.properties configured');
  return config;
};

const withSentryAuth = (config) => {
  config = withDangerousMod(config, [
    'ios',
    async (config) => {
      const token = getSentryAuthToken(config.modRequest.projectRoot);
      if (!token) {
        console.warn('[withSentryAuth] SENTRY_AUTH_TOKEN not found — source maps will not be uploaded.');
        return configureIOSWithoutToken(config);
      }
      return configureIOS(config, token);
    },
  ]);

  config = withDangerousMod(config, [
    'android',
    async (config) => {
      const token = getSentryAuthToken(config.modRequest.projectRoot);
      if (!token) {
        console.warn('[withSentryAuth] SENTRY_AUTH_TOKEN not found — source maps will not be uploaded.');
        return config;
      }
      return configureAndroid(config, token);
    },
  ]);

  return config;
};

module.exports = withSentryAuth;
