// =============================================================================
// operator-inputs.mjs — the ONE canonical schema of operator-supplied inputs
// =============================================================================
// The single source of truth for the SMALL set of values an operator must
// supply to stand up (or fork) an AISHA instance — everything a fork cannot
// DERIVE. Every stack-internal secret and every derived domain/mesh/URL is
// generated by scripts/generate-secrets.mjs + derive-domains and MUST NOT
// appear here.
//
// NOTHING provider- or model-specific is hardcoded here. The credential / BYOK
// inputs (LLM providers, mesh, email, observability, infra tokens, …) are
// PARSED at load time from config/external-secrets.required.env — the
// @-annotated source of truth that file itself designates for wizard use
// ("Parser čte @-annotated komentáře pro každý klíč"). Add a provider there,
// annotate it, and it flows into every consumer automatically; the runtime
// dynamic catalog is ai_provider_registry. This module only ADDS the non-secret
// topology / identity decisions (TLDs, namespace, admin, overlay) that are raw
// per-instance choices and live in no other SoT.
//
// Consumed by (fix-at-source — no drift between prompt, doc, and reality):
//   • scripts/operator-setup.mjs   — interactive local install/verify workbench
//   • config/fork-instance-inputs.env.example — GENERATED from this schema
//   • scripts/aisha-cold-start.sh  — prompts for the missing REQUIRED inputs
//   • the IDE add-on / a web workbench — via `operator-setup.mjs --json`
// =============================================================================
import { readFileSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const SECRETS_FILE = resolve(HERE, "../../config/external-secrets.required.env");

// ── Non-secret topology / identity inputs (raw per-instance decisions) ────────
// These are NOT credentials and live in no other SoT, so they are declared here.
// None of them is a provider or model — just the instance's shape + identity.
const NON_SECRET_INPUTS = [
  {
    key: "COOLIFY_URL",
    category: "infra-endpoints",
    label: "Coolify base URL",
    description: "Your Coolify controller's API base URL — the deploy target (the API TOKEN is a secret, sourced separately).",
    required: true,
    secret: false,
    example: "https://coolify.example.com",
  },
  {
    key: "FORGEJO_URL",
    category: "infra-endpoints",
    label: "Forgejo base URL",
    description: "Your Forgejo host — Coolify clones the stack + overlays from here (the TOKEN is a secret, sourced separately).",
    required: true,
    secret: false,
    example: "https://git.example.com",
  },
  {
    key: "PUBLIC_TLD",
    category: "topology",
    label: "Public TLD",
    description: "The instance's public apex — every public *.<PUBLIC_TLD> domain derives from it.",
    required: true,
    secret: false,
    example: "acme.example.com",
  },
  {
    key: "INTERNAL_TLD",
    category: "topology",
    label: "Internal TLD",
    description: "Per-server internal apex (direct Coolify routing, bypasses the public edge).",
    required: true,
    secret: false,
    example: "acme.internal.example.com",
  },
  {
    key: "MESH_TLD",
    category: "topology",
    label: "Mesh TLD",
    description: "WireGuard mesh apex — every <role>.<MESH_TLD> peer hostname derives from it.",
    required: true,
    secret: false,
    example: "mesh.acme.internal",
  },
  {
    key: "APP_NAME_PREFIX",
    category: "topology",
    label: "Instance namespace",
    description: "Short slug that namespaces Coolify scope, mesh ports, and (by default) the overlay repos.",
    required: true,
    secret: false,
    example: "acme",
  },
  {
    key: "AISHA_FORGEJO_ORG",
    category: "topology",
    label: "Forgejo org for overlays",
    description: "Org that holds <org>-instance-data / <org>-guru-web overlays.",
    required: false,
    secret: false,
    example: "acme",
    derive: "unset → falls back to APP_NAME_PREFIX",
  },
  // ── Operator identity ──────────────────────────────────────────────────────
  // Who RUNS this instance. Distinct from the software's own name: whoever
  // stands the platform up runs it as THEMSELVES, so none of this may carry the
  // donor's brand. It lives here rather than in a profile because it is exactly
  // what this file is for — a per-instance choice that cannot be derived from
  // anything else, and that the operator should be ASKED for.
  //
  // Each one still carries a derive rule, because "must be asked" and "has a
  // sensible suggestion" are not in conflict: an operator who skips the prompt
  // gets their own namespace back, never the donor's name.
  {
    key: "AISHA_OPERATOR_ORG",
    category: "identity",
    label: "Operator organization",
    description:
      "Organization that runs this instance. Becomes O= in the internal CA and in every certificate it issues, and the default org shown in the studio.",
    required: false,
    secret: false,
    example: "Acme Industries",
    derive: "unset → APP_NAME_PREFIX upper-cased (the instance namespace)",
  },
  {
    key: "AISHA_OPERATOR_LEGAL_NAME",
    category: "identity",
    label: "Operator legal name",
    description:
      "Full legal entity for footers, copyright and e-mail identity. Kept separate from the organization because the legal form belongs in prose, not in a certificate DN.",
    required: false,
    secret: false,
    example: "Acme Industries Ltd.",
    derive: "unset → AISHA_OPERATOR_ORG",
  },
  {
    key: "AISHA_OPERATOR_COUNTRY",
    category: "identity",
    label: "Operator country (ISO 3166-1 alpha-2)",
    description:
      "Becomes C= in the CA subject. Optional in X.509 — when unset the attribute is OMITTED rather than defaulted, because guessing a country for someone else's certificate authority is worse than leaving it out.",
    required: false,
    secret: false,
    example: "GB",
    derive: "unset → C= is omitted from the subject entirely",
  },
  {
    key: "AISHA_CA_NAME",
    category: "identity",
    label: "Internal CA name",
    description:
      "Leading part of the internal root CA common name: '<name> Root CA - <realm>'. BOOTSTRAP-ONLY — the CN is part of the CA's identity and the published CRL filename is derived from it, so changing it later means issuing a new CA, not renaming one.",
    required: false,
    secret: false,
    example: "Acme",
    derive: "unset → AISHA_OPERATOR_ORG (which itself falls back to APP_NAME_PREFIX upper-cased)",
  },
  {
    key: "AISHA_PRIMARY_ADMIN_EMAIL",
    category: "topology",
    label: "Primary admin email",
    description: "The first admin account — also the Keycloak platform admin identity. Derivable: an instance that declared its apex has already said everything needed to name its own admin, so this is only worth asking when the operator wants a mailbox that is NOT on the instance's own domain.",
    required: false,
    secret: false,
    example: "admin@acme.example.com",
    derive: "unset → admin@<PUBLIC_TLD>",
  },
  {
    key: "COOLIFY_PROJECT_NAME",
    category: "topology",
    label: "Coolify project name",
    description: "Name of the Coolify project the stack's apps live under.",
    required: true,
    secret: false,
    example: "acme",
    derive: "unset → falls back to APP_NAME_PREFIX",
  },
  {
    key: "AISHA_PROFILE",
    category: "topology",
    label: "Topology profile",
    description: "Deployment shape (single-host vs multi-host role split) — drives derive-domains.",
    required: true,
    secret: false,
    example: "cloud-single",
  },
  {
    key: "AISHA_INSTANCE_DATA_GIT_URL",
    category: "identity",
    label: "Private overlay repo URL",
    description: "The private aisha-instance-data overlay: KB + web content + Keycloak clients + operator roster.",
    required: false,
    secret: true,
    example: "https://<user>:<token>@git.example.com/acme/acme-instance-data.git#main",
    derive: "unset → derived from AISHA_FORGEJO_ORG + FORGEJO_URL + FORGEJO_API_TOKEN (community install → no overlay)",
  },
  {
    key: "operators.json",
    category: "identity",
    label: "Operator roster (file)",
    description: "Top-level operators.json in the overlay: emails + app roles. Missing KC accounts are auto-created.",
    required: false,
    secret: true,
    file: true,
    example: "docs/onboarding/instance-data-template/operators.json",
    derive: "lives in the private overlay repo (fallback: config/operators.json). See docs/onboarding/instance-data-template",
  },
  {
    key: "config/tenant.json",
    category: "identity",
    label: "Private tenant list (file)",
    description: "Optional exact tenant names for belt-and-suspenders leak detection. Gitignored, never committed.",
    required: false,
    secret: false,
    file: true,
    example: "config/tenant.json.example",
    derive: "absent → gates fall back to structural detection. See config/tenant.json.example",
  },
  {
    key: "AISHA_SEED_PROFILE",
    category: "identity",
    label: "Seed profile",
    description: "Which data layers the migrate seeds (platform / demo / instance).",
    required: false,
    secret: false,
    example: "instance",
    derive: "unset → 'instance' (platform + selected implementation + private overlay)",
  },
];

const NON_SECRET_CATEGORIES = {
  "infra-endpoints": "Infra endpoints — where your Coolify / Forgejo live (the URLs; matching tokens are secrets, below)",
  topology: "Topology — the instance's public shape: its 3 TLDs, namespace, admin, and where it deploys",
  identity: "Instance identity — which content/users/overlay make this instance itself (the private overlay repo)",
};

function slugifyCategory(header) {
  return header
    .replace(/\(.*$/, "")
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

/** Human label from a KEY (e.g. SOME_API_KEY → "Some API Key"). */
function labelFromKey(key) {
  return key
    .toLowerCase()
    .split("_")
    .map((w) => (w === "api" || w === "id" || w === "url" || w === "dsn" ? w.toUpperCase() : w.charAt(0).toUpperCase() + w.slice(1)))
    .join(" ");
}

/**
 * Parse config/external-secrets.required.env — the @-annotated SoT — into secret
 * inputs. Category comes from the `# CATEGORY:` headers; required/description/
 * source/degraded from the @annotations. Keys annotated `@generated true`
 * (regenerated by cold-start or filled by a tool post-deploy) are NOT operator
 * inputs and are skipped. Nothing here names a provider — the file does.
 */
export function parseExternalSecrets(file = SECRETS_FILE) {
  const inputs = [];
  const categories = {};
  if (!existsSync(file)) return { inputs, categories };
  let category = "external";
  let categoryHeader = "External credentials";
  let ann = {};
  for (const raw of readFileSync(file, "utf8").split(/\r?\n/)) {
    const line = raw.trim();
    const cat = line.match(/^#\s*CATEGORY:\s*(.+)$/i);
    if (cat) {
      categoryHeader = cat[1].trim();
      category = slugifyCategory(categoryHeader) || "external";
      // Registered only when it actually yields a non-generated input (below),
      // so an all-@generated category doesn't surface as an empty group.
      continue;
    }
    const at = line.match(/^#\s*@(\w+)\s*(.*)$/);
    if (at) {
      ann[at[1].toLowerCase()] = at[2].trim();
      continue;
    }
    const kv = line.match(/^([A-Z][A-Z0-9_]*)=/);
    if (kv) {
      const key = kv[1];
      const generated = /^true\b/i.test(ann.generated || "");
      if (!generated) {
        inputs.push({
          key,
          category,
          label: labelFromKey(key),
          description: ann.purpose || `${labelFromKey(key)} (external credential).`,
          required: /^true\b/i.test(ann.required || ""),
          secret: true,
          example: "", // secret — supply the real value out of band; never a placeholder token
          source: ann.source || undefined,
          degraded: ann.degraded || undefined,
          critical: ann.critical || undefined,
        });
        if (!categories[category]) categories[category] = categoryHeader;
      }
      ann = {};
      continue;
    }
    if (line === "") ann = {}; // blank line ends an annotation block with no key
  }
  return { inputs, categories };
}

const EXTERNAL = parseExternalSecrets();

/** All operator inputs: non-secret topology/identity + parsed external secrets. */
export const OPERATOR_INPUTS = [...NON_SECRET_INPUTS, ...EXTERNAL.inputs];

/** Category descriptions (non-secret static + secret categories from the file). */
export const CATEGORIES = { ...NON_SECRET_CATEGORIES, ...EXTERNAL.categories };

/** All required inputs (the instance can't come up without these). */
export function requiredInputs() {
  return OPERATOR_INPUTS.filter((i) => i.required);
}

/** Inputs grouped by category, in CATEGORIES order. */
export function byCategory() {
  const groups = {};
  for (const cat of Object.keys(CATEGORIES)) groups[cat] = [];
  for (const input of OPERATOR_INPUTS) (groups[input.category] ??= []).push(input);
  return groups;
}

/** Machine-readable contract for the IDE add-on / web workbench. */
export function toJson() {
  return { categories: CATEGORIES, inputs: OPERATOR_INPUTS };
}

/** Render the canonical config/fork-instance-inputs.env.example text. */
export function renderEnvExample() {
  const lines = [
    "# =============================================================================",
    "# fork-instance-inputs.env.example — the MINIMAL operator input set",
    "# =============================================================================",
    "# GENERATED from scripts/lib/operator-inputs.mjs — DO NOT EDIT BY HAND.",
    "# Regenerate: node scripts/operator-setup.mjs --print-env-example > config/fork-instance-inputs.env.example",
    "#",
    "# Non-secret topology/identity is declared in operator-inputs.mjs; the secret",
    "# credentials below are PARSED from config/external-secrets.required.env (its",
    "# @annotations), so providers are never hardcoded twice.",
    "#",
    "# Copy the values you need into .env.local (gitignored) or your environment,",
    "# then run:  node scripts/operator-setup.mjs   (interactive setup + local verify).",
    "# Every secret and every domain the stack needs to run ITSELF is generated/derived.",
    "# =============================================================================",
    "",
  ];
  const groups = byCategory();
  for (const [cat, meta] of Object.entries(CATEGORIES)) {
    const inputs = groups[cat];
    if (!inputs?.length) continue;
    lines.push(`# ── ${meta}`);
    for (const i of inputs) {
      const tags = [
        i.required ? "REQUIRED" : "optional",
        i.secret ? "secret" : null,
        i.file ? "file" : null,
      ].filter(Boolean);
      lines.push(`# ${i.label} [${tags.join(", ")}] — ${i.description}`);
      if (i.source) lines.push(`#   get it: ${i.source}`);
      if (i.degraded) lines.push(`#   without it: ${i.degraded}`);
      if (i.derive) lines.push(`#   default: ${i.derive}`);
      if (i.file) {
        lines.push(`#   ${i.key} — see ${i.example}`);
      } else if (i.secret) {
        lines.push(`${i.key}=`);
      } else {
        lines.push(`${i.key}=${i.example}`);
      }
      lines.push("");
    }
  }
  return lines.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd() + "\n";
}
