/**
 * Legacy Domain Gate Test
 *
 * AISHA stack must use *.aisha.guru domains. The legacy *.id3a.cz cluster
 * was retired during the V2 cutover. This gate scans the active workspace
 * for forbidden references and forces explicit allow-listing of the few
 * legitimate exceptions (infra, external services, tenant data).
 *
 * If a new file slips in with an unmapped *.id3a.cz domain, this test fails
 * and points to the offending location. The companion script
 *   scripts/rebrand-id3a-to-aisha-guru.sh
 * applies the systemic fix.
 *
 * Run via: npm run test:gates
 */

import { describe, it, expect } from "vitest";
import { execFileSync } from "node:child_process";
import fs from "fs";
import path from "path";
import { getServerRoles } from "./lib/domain-topology";

const ROOT = path.resolve(__dirname, "../../..");

// Recursive walk respecting ignore list.
const IGNORE_DIRS = new Set([
  "node_modules",
  "dist",
  ".git",
  ".claude", // git worktrees + local Claude agent state — not production code
  "trash",
  "archive",
  "playwright-report",
  "test-results",
  "coverage",
  ".next",
  ".turbo",
  ".cache",
]);

// Files where references are LEGITIMATE and must NOT be flagged.
// Each entry is workspace-relative.
//
// TENANT FORK EXTENSION POINT: tenant forks (e.g. acme, globex, …) declare
// their tenant-data + docs files here. This list names only PLATFORM file
// PATHS (not tenants), so it is public-safe as-is; the exact tenant NAME list
// lives OUT of the public tree in the gitignored config/tenant.json (see
// config/tenant.json.example + src/tests/gates/lib/tenant-leak-detect.ts) — a
// committed denylist of real customers would itself disclose them.
const FILE_ALLOWLIST = new Set<string>([
  // Tenant data — multi-tenant production seed.
  "aisha/db/seed.instance.sql",
  // Compiled seed artifacts: generated by `npm run db:seed:compile` (default
  // profile=full) from the sources above. They inherit the allow-listing of
  // seed.instance.sql (the only seed source carrying real external-project
  // domains). core/translations/demo source files are still scanned directly,
  // so coverage is not reduced — these derivatives just avoid double-flagging.
  "aisha/db/seed.compiled.sql",
  "aisha/db/seed.sql",
  // Coolify infrastructure config: per-server tenant FQDN list (not AISHA stack).
  "coolify/servers.json",
  // Keycloak realm export: tenant client redirect URIs (not AISHA stack).
  "keycloak/aisha-realm.json",
  // Multi-server topology narrative with historical examples (game/staging).
  "docs/deploy/MULTI_SERVER_COOLIFY.md",
  // This gate test references the strings.
  "src/tests/gates/legacy-domains.gate.test.ts",
  // The domain zoning gate test references the strings.
  "src/tests/gates/domain-zoning.gate.test.ts",
  // These instance-data gates detect tenant leakage STRUCTURALLY (Keycloak
  // client allowlist, seed compile-profile, email shape) + an optional private
  // config/tenant.json — they name no tenant themselves. Kept on the allowlist
  // as harmless (they reference only safe placeholder/platform domains).
  "src/tests/gates/no-instance-data-in-public.gate.test.ts",
  "src/tests/gates/public-oss-boundary.gate.test.ts",
  // Single source of truth for domain zoning (PUBLIC vs INTERNAL).
  "config/domains.env",
  // NOTE: tenant forks do NOT need per-file allow-listing here. The three-zone
  // model below (getDomainZones) reads each deployment's PUBLIC / INTERNAL /
  // MESH TLDs from its OWN config/domains*.env overlay and accepts references
  // in those zones generically — so a fork declaring e.g.
  // PUBLIC_TLD=staging.id3a.cz passes without ever editing this list.
]);

// Per-server INTERNAL admin zone: <svc>.<server>.<INTERNAL_TLD> is legitimate
// when <server> is a cluster node. Roles are read DYNAMICALLY from the topology
// SoT (coolify/servers.json) via the shared helper — never hardcoded — so the
// design stays dynamic per deployment. Server HOSTNAMES (talos, giah, …) are
// auto-derived separately from declared <host>.<INTERNAL_TLD> values in config
// (see getDomainZones step 3).
const KNOWN_SERVERS = getServerRoles();

// Subdomains that are intentionally allowed to remain on id3a.cz.
// Infra aliases:
//   - frontend.id3a.cz, coolify.id3a.cz: Coolify management endpoints
//   - repo.id3a.cz, git.id3a.cz:      Forgejo Git remote
// External services (NOT part of AISHA stack):
//   - sentry.id3a.cz, npm.id3a.cz
// Generic doc placeholders / anti-pattern references:
//   - my-service.id3a.cz, service.id3a.cz, domain.id3a.cz, another.id3a.cz
//   - studio.id3a.cz: kept as ANTI-PATTERN reference in knowledge base
//     ("NIKDY nepoužívej studio.id3a.cz — správná doména je db.aisha.guru")
const ALLOWED_SUBDOMAINS = new Set<string>([
  "frontend",
  "repo",
  "git",
  "coolify",
  "sentry",
  "npm",
  "my-service",
  "service",
  "domain",
  "another",
  "studio",
]);

/**
 * The deployment's THREE domain ZONES, read from the SoT (config/domains.env,
 * config/domains-*.env overlays, config/domains.env.example, coolify-environments.env).
 *
 * Why: this gate's premise ("id3a.cz is the retired domain; use aisha.guru") is
 * only ONE deployment variant. The platform is MULTITENANT — every deployment
 * declares its own three TLD zones in its own SoT (per the config/domains.env
 * header), and the gate validates references against THOSE:
 *
 *   PUBLIC_TLD    — edge / client-facing routes (web, api, auth). Any subdomain
 *                   is legitimate (`*.${PUBLIC_TLD}`).
 *   INTERNAL_TLD  — per-server admin/system addressing. Legitimate ONLY in the
 *                   `<svc>.<server>.${INTERNAL_TLD}` / `<server>.${INTERNAL_TLD}`
 *                   shape (server ∈ the deployment's servers).
 *   MESH_TLD      — NetBird peer-to-peer mesh DNS. Any subdomain legitimate.
 *
 * So a fork whose SoT says PUBLIC_TLD=staging.id3a.cz uses *.staging.id3a.cz
 * legitimately, while the SAME id3a.cz string is flagged for a deployment whose
 * config never declares it. Generic + multitenant: no hardcoded TLD, no
 * per-file/per-fork allow-listing of tenant domains.
 */
interface DomainZones {
  publicTlds: Set<string>; // host under one of these → PUBLIC (any subdomain ok)
  meshTlds: Set<string>; // host under one of these → MESH (any subdomain ok)
  internalTlds: Set<string>; // host valid ONLY as <…>.<server>.<TLD> / <server>.<TLD>
  servers: Set<string>; // server segments valid in the INTERNAL zone
}

const DEPLOYMENT_CFG_FILES = ((): string[] => {
  const files = [
    "config/domains.env",
    "config/domains.env.example",
    "config/coolify-environments.env",
  ];
  try {
    for (const f of fs.readdirSync(path.join(ROOT, "config"))) {
      if (/^domains-.*\.env$/.test(f)) files.push(`config/${f}`);
    }
  } catch {
    /* no config/ dir */
  }
  return files;
})();

function readEnvKey(txt: string, key: string): string | null {
  const m = txt.match(new RegExp(`^\\s*${key}=([^\\s#$]+)`, "m"));
  return m && m[1].trim() ? m[1].trim().toLowerCase() : null;
}

/** True when `host` equals or sits under any TLD in `tlds`. */
function isUnder(host: string, tlds: Set<string>): boolean {
  for (const t of tlds) if (host === t || host.endsWith("." + t)) return true;
  return false;
}

function getDomainZones(): DomainZones {
  const publicTlds = new Set<string>();
  const meshTlds = new Set<string>();
  const internalTlds = new Set<string>();
  const servers = new Set<string>(KNOWN_SERVERS);

  const texts: string[] = [];
  for (const rel of DEPLOYMENT_CFG_FILES) {
    try {
      texts.push(fs.readFileSync(path.join(ROOT, rel), "utf8"));
    } catch {
      /* missing overlay */
    }
  }

  // 1. Explicit zone TLDs (PUBLIC_TLD / INTERNAL_TLD / MESH_TLD), + the mesh
  //    TLD derived from NETBIRD_MESH_HOST (e.g. netbird.mesh.aisha.internal).
  for (const txt of texts) {
    const pub = readEnvKey(txt, "PUBLIC_TLD");
    if (pub) publicTlds.add(pub);
    const intl = readEnvKey(txt, "INTERNAL_TLD");
    if (intl) internalTlds.add(intl);
    const mesh = readEnvKey(txt, "MESH_TLD");
    if (mesh) meshTlds.add(mesh);
    const meshHost = readEnvKey(txt, "NETBIRD_MESH_HOST");
    if (meshHost) {
      const labels = meshHost.split(".");
      if (labels.length >= 3) meshTlds.add(labels.slice(1).join("."));
    }
  }

  // 2. Derive the PUBLIC zone from declared concrete public domains (a fork may
  //    set *_DOMAIN / WEB_FQDNS instead of PUBLIC_TLD): the parent-zone of e.g.
  //    APP_DOMAIN=cheers.staging.id3a.cz is staging.id3a.cz.
  const PUBLIC_KEYS = ["APP_DOMAIN", "API_DOMAIN", "API_DOMAIN_PUBLIC", "KEYCLOAK_DOMAIN_PUBLIC", "WEB_FQDNS"];
  for (const txt of texts) {
    for (const key of PUBLIC_KEYS) {
      const v = readEnvKey(txt, key);
      if (!v) continue;
      for (const raw of v.split(",")) {
        const host = raw.replace(/^https?:\/\//, "").split("/")[0].trim();
        const labels = host.split(".");
        if (labels.length >= 3) publicTlds.add(labels.slice(1).join("."));
      }
    }
  }

  // 3. Derive INTERNAL servers: hosts under an INTERNAL_TLD that are NOT in the
  //    public/mesh zone contribute their server segment (talos.id3a.cz → talos;
  //    db.giah.id3a.cz → giah; pki-bridge.backend.id3a.cz → backend).
  const HOST_RE = /\b([a-z0-9-]+(?:\.[a-z0-9-]+)*\.[a-z]{2,})\b/gi;
  for (const txt of texts) {
    HOST_RE.lastIndex = 0;
    let m: RegExpExecArray | null;
    while ((m = HOST_RE.exec(txt)) !== null) {
      const host = m[1].toLowerCase();
      if (isUnder(host, publicTlds) || isUnder(host, meshTlds)) continue;
      for (const itld of internalTlds) {
        if (host !== itld && host.endsWith("." + itld)) {
          const prefix = host.slice(0, -(itld.length + 1)).split(".");
          servers.add(prefix[prefix.length - 1]);
        }
      }
    }
  }

  return { publicTlds, meshTlds, internalTlds, servers };
}

const ZONES = getDomainZones();

/** True when `host` falls into one of the deployment's three configured zones. */
function isInConfiguredZone(host: string): boolean {
  const h = host.toLowerCase();
  if (isUnder(h, ZONES.publicTlds)) return true; // PUBLIC zone
  if (isUnder(h, ZONES.meshTlds)) return true; // MESH zone
  for (const itld of ZONES.internalTlds) {
    // INTERNAL zone: <…>.<server>.<INTERNAL_TLD> or <server>.<INTERNAL_TLD>.
    if (!h.endsWith("." + itld)) continue;
    const prefix = h.slice(0, -(itld.length + 1)).split(".");
    if (ZONES.servers.has(prefix[prefix.length - 1])) return true;
  }
  return false;
}

const LEGACY_HOST_RE = /([a-z0-9-]+(?:\.[a-z0-9-]+)*)\.id3a\.cz/gi;

// `realms/evymo` — old Keycloak realm name (now `realms/aisha`).
const LEGACY_REALM_RE = /realms\/evymo\b/g;

interface Violation {
  file: string;
  line: number;
  match: string;
  hint: string;
}

function walk(dir: string, acc: string[]): void {
  let entries: fs.Dirent[];
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch {
    return;
  }
  for (const entry of entries) {
    if (entry.name.startsWith(".") && entry.name !== ".github" && entry.name !== ".vscode" && entry.name !== ".mcp.json") {
      // skip hidden by default, except whitelisted ones we DO want to scan
    }
    if (IGNORE_DIRS.has(entry.name)) continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      walk(full, acc);
    } else if (entry.isFile()) {
      acc.push(full);
    }
  }
}

const TEXT_EXT = new Set([
  ".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs",
  ".json", ".yml", ".yaml", ".toml",
  ".md", ".sh", ".env",
  ".sql", ".conf",
]);

function isScannable(file: string): boolean {
  const base = path.basename(file);
  if (base === "package-lock.json" || base === "bun.lockb") return false;
  if (base.endsWith(".lock")) return false;
  const ext = path.extname(file);
  if (TEXT_EXT.has(ext)) return true;
  // Dockerfile, .env without ext
  if (base === "Dockerfile" || base.startsWith("Dockerfile.")) return true;
  if (base.startsWith(".env")) return true;
  return false;
}

function relPath(abs: string): string {
  return path.relative(ROOT, abs).split(path.sep).join("/");
}

function scanFile(abs: string): Violation[] {
  const rel = relPath(abs);
  if (FILE_ALLOWLIST.has(rel)) return [];

  let content: string;
  try {
    content = fs.readFileSync(abs, "utf8");
  } catch {
    return [];
  }
  const lines = content.split("\n");
  const violations: Violation[] = [];

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];

    // ⛔ 2026-08-25: ŘÁDKOVÁ VÝJIMKA pro DOLOŽENÝ INCIDENT.
    //
    // Výjimky tu byly jen na celý soubor nebo celou subdoménu. Když se
    // v `aisha-cold-start.sh` zaznamenal naměřený incident (`NETBIRD_MESH_HOST`
    // ukotvený v opuštěné zóně → pki-bridge odmítl SAN → vlna 5 stála), musela
    // ta VADNÁ adresa zůstat v komentáři doslova — je to důkaz, ne reference.
    // Allow-listnout kvůli tomu nejadresnější soubor v repu by bránu vypnulo.
    //
    // Anotace je proto úzká a opt-in: platí pro JEDEN řádek, musí nést důvod
    // a je grepovatelná (`rg 'legacy-domains: doloz'`). Živá reference takovou
    // značku nemá, takže padá dál.
    if (/legacy-domains:\s*dolozen/i.test(line)) continue;

    // Domain check
    LEGACY_HOST_RE.lastIndex = 0;
    let m: RegExpExecArray | null;
    while ((m = LEGACY_HOST_RE.exec(line)) !== null) {
      const captured = m[1].toLowerCase();
      const parts = captured.split(".");
      // INTERNAL zone: <svc>.<server>.id3a.cz where <server> is a known node.
      if (parts.length >= 2 && KNOWN_SERVERS.has(parts[parts.length - 1])) continue;
      // Bare per-server zone: <server>.id3a.cz (e.g. cookie domain `.backend.id3a.cz`).
      if (parts.length === 1 && KNOWN_SERVERS.has(parts[0])) continue;
      // Single-label legacy host: must be in the explicit allow-list.
      if (parts.length === 1 && ALLOWED_SUBDOMAINS.has(parts[0])) continue;
      // Deployment-configured zone (from the SoT, config/domains*.env): the host
      // sits in this deployment's PUBLIC / INTERNAL / MESH zone, so it's a
      // current domain, not a retired one. Multitenant — each deployment's own
      // three-zone config decides.
      if (isInConfiguredZone(m[0])) continue;
      violations.push({
        file: rel,
        line: i + 1,
        match: m[0],
        hint: `Replace with .aisha.guru equivalent or use the INTERNAL zone <svc>.<server>.id3a.cz (server ∈ ${[...KNOWN_SERVERS].join(",")}). See config/domains.env.`,
      });
    }

    // Realm check
    LEGACY_REALM_RE.lastIndex = 0;
    if (LEGACY_REALM_RE.test(line)) {
      violations.push({
        file: rel,
        line: i + 1,
        match: "realms/evymo",
        hint: "Keycloak realm renamed to 'aisha'. Use realms/aisha.",
      });
    }
  }
  return violations;
}

describe("Legacy domain gate (id3a.cz → aisha.guru)", () => {
  it("AISHA stack must not reference *.id3a.cz subdomains outside the allow-list", () => {
    // PERFORMANCE: pre-filter via `git grep` (uses git index, scans only
    // tracked files, microsecond startup). Returns only files that contain
    // "id3a.cz" or "realms/evymo" — typically <100 files. Then we scan
    // THOSE for line-precise violations + allowlist checks.
    //
    // Without pre-filter, the test reads 23k files sequentially in Node,
    // taking 40s+ solo and timing out at 120s under parallel suite load.
    // git grep is ~5s vs grep -r ~97s vs Node fs walk ~42s.
    let candidates: string[];
    try {
      const out = execFileSync("git", [
        "grep",
        "-lE",
        "id3a\\.cz|realms/evymo",
      ], {
        cwd: ROOT,
        encoding: "utf-8",
        stdio: ["ignore", "pipe", "pipe"],
      });
      candidates = out
        .split("\n")
        .filter(Boolean)
        // Apply the same IGNORE_DIRS filter as the original walk (git grep
        // includes tracked files in .claude/, archive/ etc. that the walk
        // explicitly skipped)
        .filter((rel) => {
          const segments = rel.split("/");
          for (const seg of segments) {
            if (IGNORE_DIRS.has(seg)) return false;
          }
          return true;
        })
        // Filter by extension same as isScannable
        .filter((rel) => isScannable(rel))
        // git grep returns paths relative to repo root — make them absolute
        .map((rel) => path.join(ROOT, rel));
    } catch (err: unknown) {
      // git grep exit 1 = no matches — empty candidate list, test passes.
      const e = err as { status?: number };
      if (e.status === 1) {
        candidates = [];
      } else {
        throw err;
      }
    }

    const violations: Violation[] = [];
    for (const f of candidates) {
      violations.push(...scanFile(f));
    }

    if (violations.length > 0) {
      const report = violations
        .slice(0, 50)
        .map((v) => `  ${v.file}:${v.line}  ${v.match}\n      → ${v.hint}`)
        .join("\n");
      const more =
        violations.length > 50 ? `\n  …and ${violations.length - 50} more.` : "";
      throw new Error(
        `Found ${violations.length} legacy domain reference(s):\n${report}${more}\n\n` +
          `Allowed subdomains: ${[...ALLOWED_SUBDOMAINS].join(", ")}\n` +
          `Allow-listed files: ${[...FILE_ALLOWLIST].join(", ")}`,
      );
    }

    expect(violations.length).toBe(0);
  });
});
