/**
 * Mesh on/off Toggle — Integral Design Gate
 *
 * Enforces a SINGLE switch (`MESH_ENABLED`) that controls how the edge stack
 * reaches backend services on a different server (Frontend→Backend).
 *
 *   off (default): edge-proxy → public TLS to *.backend.id3a.cz via Backend's
 *                  Traefik. Cross-server reach without mesh dependency.
 *                  Stable cold-start state.
 *   on:            edge-proxy → mesh-router (DNAT) → wt0 → core peer
 *                  over WireGuard.
 *
 * Why this gate exists:
 *   Pre-fix the edge compose hardcoded `https://api.backend.id3a.cz` as the
 *   "transitional fallback" (memory: feedback_split_arch_mesh_routing.md).
 *   That made the routing strategy implicit — flipping to mesh required
 *   editing compose + redeploying, with no audit trail or quick rollback.
 *
 *   Now the strategy is declarative + togglable at runtime via
 *   scripts/aisha-mesh-toggle.mjs (env PATCH + force redeploy in one step).
 *
 * The contract enforced here:
 *   1) docker-compose.coolify-prebuilt.yml has MESH_ENABLED env on edge-proxy
 *   2) Both *_UPSTREAM_MESH and *_UPSTREAM_PUBLIC topology vars are required
 *   3) Entrypoint resolves MCP/API/DIRIGENT_UPSTREAM based on MESH_ENABLED
 *   4) Default value is 'false' (cold-start brings up without mesh dependency)
 *   5) config/domains.env declares MESH_ENABLED=false
 *   6) coolify-deploy-init.sh propagates MESH_ENABLED to aisha-edge
 *   7) aisha-cold-start.sh persists MESH_ENABLED to .env.coolify
 *   8) scripts/aisha-mesh-toggle.mjs exists + supports --on/--off/--status
 */
import { describe, expect, test } from "vitest";
import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const ROOT = process.cwd();
const PREBUILT_COMPOSE = join(ROOT, "docker-compose.coolify-prebuilt.yml");
const DOMAINS_ENV = join(ROOT, "config/domains.env");
const DEPLOY_INIT = join(ROOT, "scripts/coolify-deploy-init.sh");
const COLD_START = join(ROOT, "scripts/aisha-cold-start.sh");
const TOGGLE_SCRIPT = join(ROOT, "scripts/aisha-mesh-toggle.mjs");

describe("MESH on/off Toggle — Integral Design", () => {
  test("edge-proxy compose declares MESH_ENABLED env + required mesh/public upstream contract", () => {
    const compose = readFileSync(PREBUILT_COMPOSE, "utf-8");

    // Find edge-proxy service block
    const edge = compose.match(/^\s+edge-proxy:[\s\S]+?(?=\n {2}[a-z]|\nvolumes:|\nnetworks:)/m);
    expect(edge, "edge-proxy block must be parseable").toBeTruthy();
    if (!edge) return;
    const block = edge[0];

    // 1) MESH_ENABLED env var
    expect(
      block,
      "edge-proxy MUST declare MESH_ENABLED env (single global switch).",
    ).toMatch(/MESH_ENABLED:\s*\$\{MESH_ENABLED:\?MESH_ENABLED must be generated by topology resolver\}/);

    // 2) Mesh-mode topology values are required, not hardcoded compose fallbacks.
    expect(
      block,
      "edge-proxy MUST require MCP_UPSTREAM_MESH from topology resolver (used when MESH_ENABLED=true).",
    ).toMatch(/MCP_UPSTREAM_MESH:\s*\$\{MCP_UPSTREAM_MESH:\?MCP_UPSTREAM_MESH must be generated by topology resolver\}/);
    expect(block).toMatch(/API_UPSTREAM_MESH:\s*\$\{API_UPSTREAM_MESH:\?API_UPSTREAM_MESH must be generated by topology resolver\}/);
    expect(block).toMatch(/DIRIGENT_UPSTREAM_MESH:\s*\$\{DIRIGENT_UPSTREAM_MESH:\?DIRIGENT_UPSTREAM_MESH must be generated by topology resolver\}/);

    // 3) Public-mode topology values are required, not hardcoded compose fallbacks.
    expect(
      block,
      "edge-proxy MUST require MCP_UPSTREAM_PUBLIC from topology resolver (used when MESH_ENABLED=false).",
    ).toMatch(/MCP_UPSTREAM_PUBLIC:\s*\$\{MCP_UPSTREAM_PUBLIC:\?MCP_UPSTREAM_PUBLIC must be generated by topology resolver\}/);
    expect(block).toMatch(/API_UPSTREAM_PUBLIC:\s*\$\{API_UPSTREAM_PUBLIC:\?API_UPSTREAM_PUBLIC must be generated by topology resolver\}/);
    expect(block).toMatch(/DIRIGENT_UPSTREAM_PUBLIC:\s*\$\{DIRIGENT_UPSTREAM_PUBLIC:\?DIRIGENT_UPSTREAM_PUBLIC must be generated by topology resolver\}/);
    expect(block).toMatch(/AUTH_UPSTREAM_PUBLIC:\s*\$\{AUTH_UPSTREAM_PUBLIC:\?AUTH_UPSTREAM_PUBLIC must be generated by topology resolver\}/);

    // 4) Per-service overrides MUST be empty by default (so the
    //    mesh/public switch determines the upstream unless operator pins).
    expect(
      block,
      "MCP_UPSTREAM/API_UPSTREAM/DIRIGENT_UPSTREAM must default to empty so the mesh/public switch governs the upstream.",
    ).toMatch(/MCP_UPSTREAM:\s*\$\{MCP_UPSTREAM:-\}/);
  });

  test("edge-proxy entrypoint resolves upstreams based on MESH_ENABLED", () => {
    const compose = readFileSync(PREBUILT_COMPOSE, "utf-8");

    // Look for the entrypoint resolver — should branch on MESH_ENABLED
    expect(
      compose,
      "entrypoint MUST branch on MESH_ENABLED to derive upstream URLs.",
    ).toMatch(/case[\s\S]*?MESH_ENABLED[\s\S]*?true\|1\|yes\|on/i);

    // Both branches set MCP/API/DIRIGENT_UPSTREAM. Compose escapes $ → $$
    // in entrypoint string so the host's docker compose passes literal $
    // to the container shell. Match either form.
    expect(
      compose,
      "MESH_ENABLED=true branch must set MCP_UPSTREAM from MCP_UPSTREAM_MESH.",
    ).toMatch(/MCP_UPSTREAM="\$+\{MCP_UPSTREAM:-\$+\{MCP_UPSTREAM_MESH/);
    expect(
      compose,
      "MESH_ENABLED=false branch must set MCP_UPSTREAM from MCP_UPSTREAM_PUBLIC.",
    ).toMatch(/MCP_UPSTREAM="\$+\{MCP_UPSTREAM:-\$+\{MCP_UPSTREAM_PUBLIC/);

    // Logs which mode is active (operator visibility)
    expect(
      compose,
      "entrypoint should announce MESH_MODE in its startup log so operators can see which path is active.",
    ).toMatch(/MESH_MODE/);
  });

  test("config/domains.env declares mesh ZAPNUTOU — je to podmínka, ne volba", () => {
    // ⛔ ZMĚNA ROZHODNUTÍ 2026-08-26. Dřív tu stálo `MESH_ENABLED=false` jako
    // „stabilní stav cold-startu". Naměřený následek: resolver s vypnutou meshí
    // plnil `*_UPSTREAM_MESH` NEMESHOVOU adresou (slotovou zónou), edge jel
    // v režimu `public`, a mesh — ač vznikla a peeři byli `connected` —
    // nepoužívala ANI JEDNA služba. Nic přitom nespadlo.
    //
    // Záměr téhle brány se NEMĚNÍ: strategie musí být DEKLAROVANÁ, ne zadrátovaná
    // v composu (to je důvod, proč vznikla). Mění se jen deklarovaná hodnota:
    // mesh je podmínka provozu AISHA stacku, takže výchozí stav je ZAPNUTO.
    const env = readFileSync(DOMAINS_ENV, "utf-8");
    expect(
      env,
      "config/domains.env MUSÍ deklarovat MESH_ENABLED=true — mesh není volitelný doplněk.",
    ).toMatch(/^MESH_ENABLED=true\s*$/m);
  });

  test("coolify-deploy-init.sh propagates MESH_ENABLED + upstream defaults to aisha-edge", () => {
    const sh = readFileSync(DEPLOY_INIT, "utf-8");

    // Must set MESH_ENABLED on the edge app (in the web|edge case)
    expect(
      sh,
      "coolify-deploy-init.sh MUST set MESH_ENABLED on aisha-edge.",
    ).toMatch(/set_coolify_env\s+"\$local_uuid"\s+"MESH_ENABLED"/);

    // Must explicitly push generated *_UPSTREAM_MESH and *_UPSTREAM_PUBLIC values.
    expect(
      sh,
      "coolify-deploy-init.sh MUST explicitly push MCP_UPSTREAM_PUBLIC default to aisha-edge env.",
    ).toMatch(/set_coolify_env\s+"\$local_uuid"\s+"MCP_UPSTREAM_PUBLIC"/);
    expect(sh).toMatch(/set_coolify_env\s+"\$local_uuid"\s+"API_UPSTREAM_PUBLIC"/);
    expect(sh).toMatch(/set_coolify_env\s+"\$local_uuid"\s+"DIRIGENT_UPSTREAM_PUBLIC"/);
    expect(sh).toMatch(/set_coolify_env\s+"\$local_uuid"\s+"MCP_UPSTREAM_MESH"/);
    expect(sh).toMatch(/set_coolify_env\s+"\$local_uuid"\s+"API_UPSTREAM_MESH"/);
    expect(sh).toMatch(/set_coolify_env\s+"\$local_uuid"\s+"DIRIGENT_UPSTREAM_MESH"/);
  });

  test("aisha-cold-start.sh persists MESH_ENABLED + upstream defaults to .env.coolify", () => {
    const sh = readFileSync(COLD_START, "utf-8");
    expect(
      sh,
      "aisha-cold-start.sh MUST persist generated MESH_ENABLED in the .env.coolify HEREDOC.",
      ).toMatch(/MESH_ENABLED=\$\{MESH_ENABLED\}/);

      // Mesh + public upstreams are resolver output values persisted across
      // wipes and propagated to aisha-edge via deploy-init.
      expect(sh).toMatch(/MCP_UPSTREAM_PUBLIC=\$\{MCP_UPSTREAM_PUBLIC\}/);
      expect(sh).toMatch(/API_UPSTREAM_PUBLIC=\$\{API_UPSTREAM_PUBLIC\}/);
      expect(sh).toMatch(/DIRIGENT_UPSTREAM_PUBLIC=\$\{DIRIGENT_UPSTREAM_PUBLIC\}/);
      expect(sh).toMatch(/AUTH_UPSTREAM_PUBLIC=\$\{AUTH_UPSTREAM_PUBLIC\}/);
      expect(sh).toMatch(/MCP_UPSTREAM_MESH=\$\{MCP_UPSTREAM_MESH\}/);
      expect(sh).toMatch(/API_UPSTREAM_MESH=\$\{API_UPSTREAM_MESH\}/);
      expect(sh).toMatch(/DIRIGENT_UPSTREAM_MESH=\$\{DIRIGENT_UPSTREAM_MESH\}/);
      expect(sh).toMatch(/AUTH_UPSTREAM_MESH=\$\{AUTH_UPSTREAM_MESH\}/);
  });

  test("scripts/aisha-mesh-toggle.mjs exists with --on/--off/--status modes", () => {
    expect(existsSync(TOGGLE_SCRIPT), "aisha-mesh-toggle.mjs must exist").toBe(true);
    if (!existsSync(TOGGLE_SCRIPT)) return;

    const sh = readFileSync(TOGGLE_SCRIPT, "utf-8");
    expect(sh, "toggle MUST support --status").toMatch(/--status/);
    expect(sh, "toggle MUST support --on").toMatch(/--on/);
    expect(sh, "toggle MUST support --off").toMatch(/--off/);

    // Calls Coolify API: PATCH envs/bulk + POST /deploy
    expect(sh, "toggle MUST PATCH /envs/bulk on aisha-edge").toMatch(/envs\/bulk/);
    expect(sh, "toggle MUST trigger redeploy via /deploy").toMatch(/\/deploy\?uuid=/);
  });
});
