import { describe, it, expect } from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';
// The verdict has ONE owner, shared with scripts/gen-mesh-conformance-baseline.mjs
// — a second implementation would drift, and the drift would read as progress.
import { meshServices, nonMeshStacks, ownPublicRouterOffenders } from '../../../scripts/lib/mesh-conformance.mjs';

/**
 * Gate: the network shape the instance declares — inbound only through edge,
 * internally everything on the mesh.
 *
 * Owner's decision, 2026-07-30: "dovnitř jde jen přes edge se dostat a vnitřně
 * vše v mesh." Two rules follow, and this gate measures both.
 *
 * ── Why a gate before the migration, not after ──────────────────────────────
 * Converting every stack is a migration whose intermediate states look healthy:
 * measured on a production instance the same day, INBOUND /chat already travelled over the mesh
 * (`remoteAddress` was the mesh-router peer) while OUTBOUND had no route at all.
 * Half an edge works, the other half is never exercised — until it is. Without a
 * measure of "who should be on the mesh", the conversion has no definition of
 * done and a hybrid can pass as finished.
 *
 * ── Universe comes from the CATALOG, never from a literal ───────────────────
 * `mesh-agent-internal-resolution.gate.test.ts` pins four compose files by name.
 * It is green and it cannot see `ai-chat`, because a hand-written universe only
 * measures what someone remembered. Here the universe is derived: a service the
 * topology gives an INTERNAL (mesh) URL is a service that must be reachable on
 * the mesh. That derivation grows on its own when the catalog does.
 *
 * ── Why netns and not just an agent ─────────────────────────────────────────
 * Measured: `svc-potok` ships a netbird agent in its stack and still has no route
 * to 100.64.0.0/10. The agent owns `wt0` inside ITS OWN namespace; a sibling on
 * the bridge network inherits nothing. The only containers on the host that can use
 * the mesh — mesh-router, core/potok/local-ingest mesh-ingress — all share the
 * agent's namespace. So carrying an agent is necessary and NOT sufficient.
 */

const ROOT = process.cwd();
const catalog = JSON.parse(fs.readFileSync(path.join(ROOT, 'config/services.json'), 'utf8'));
const BASELINE = path.join(ROOT, 'src/tests/gates/mesh-inside-edge-outside.baseline.json');

/**
 * The conversion is a migration, not a patch, so the gate ratchets instead of
 * blocking: today's non-conformant stacks are snapshotted and the list may only
 * SHRINK. A new offender fails, and so does a stale entry — a stack that became
 * conformant must leave the list, which keeps it an honest TODO rather than a
 * place to hide. Same model as ci-service-compose-deployability.
 *
 * ⚠️ The file is REGENERATED by scripts/gen-mesh-conformance-baseline.mjs, never
 * hand-edited: a generated artefact tempts an editor exactly when it conflicts,
 * and the next regeneration silently overwrites the edit.
 */
const baseline = JSON.parse(fs.readFileSync(BASELINE, 'utf8')) as {
  stacks_without_mesh: string[];
  own_public_router: string[];
};


function ratchet(name: string, actual: string[], known: string[]): void {
  const appeared = actual.filter((x) => !known.includes(x));
  const fixed = known.filter((x) => !actual.includes(x));
  expect(appeared, `${name}: NEW offender — the migration must not grow`).toEqual([]);
  expect(
    fixed,
    `${name}: these are conformant now — regenerate the baseline ` +
      `(npm run gate:mesh:baseline) so the list stays an honest TODO`,
  ).toEqual([]);
}

describe('inbound only through edge', () => {
  it('no NEW stack publishes its own public host', () => {
    ratchet('own_public_router', ownPublicRouterOffenders(), baseline.own_public_router);
  });
});

describe('internally everything on the mesh', () => {
  it('the catalog yields a non-empty universe (a gate over nothing is worse than none)', () => {
    expect(meshServices().length).toBeGreaterThan(0);
  });

  it('no NEW stack is off the mesh, and fixed ones have left the list', () => {
    ratchet('stacks_without_mesh', nonMeshStacks(), baseline.stacks_without_mesh);
  });
});
