// Package app — AISHA Chain Application
//
// Wires together all Cosmos SDK modules into the AISHA app-chain.
// This is a minimal but functional Cosmos app with:
// - Standard modules (auth, bank, gov, staking, mint, etc.)
// - Custom x/tokenledger module (audit mirror for token ops)
// - Custom x/auditlog module (immutable journal)
//
// The chain uses:
// - uash as native staking/gas denom (1 ASH = 1_000_000 uash)
// - ugovernance as governance token denom
package app

import (
	"os"
	"path/filepath"

	"cosmossdk.io/log"
	dbm "github.com/cosmos/cosmos-db"
	"github.com/cosmos/cosmos-sdk/baseapp"
	"github.com/cosmos/cosmos-sdk/client"
	cmtservice "github.com/cosmos/cosmos-sdk/client/grpc/cmtservice"
	nodeservice "github.com/cosmos/cosmos-sdk/client/grpc/node"
	"github.com/cosmos/cosmos-sdk/codec"
	codectypes "github.com/cosmos/cosmos-sdk/codec/types"
	sdkserver "github.com/cosmos/cosmos-sdk/server"
	"github.com/cosmos/cosmos-sdk/server/api"
	serverconfig "github.com/cosmos/cosmos-sdk/server/config"
	servertypes "github.com/cosmos/cosmos-sdk/server/types"
	"github.com/cosmos/cosmos-sdk/types/module"
	"github.com/cosmos/cosmos-sdk/x/auth"
	authkeeper "github.com/cosmos/cosmos-sdk/x/auth/keeper"
	authtx "github.com/cosmos/cosmos-sdk/x/auth/tx"
	authtypes "github.com/cosmos/cosmos-sdk/x/auth/types"
	"github.com/cosmos/cosmos-sdk/x/bank"
	bankkeeper "github.com/cosmos/cosmos-sdk/x/bank/keeper"
	"github.com/cosmos/cosmos-sdk/x/consensus"
	"github.com/cosmos/cosmos-sdk/x/crisis"
	"github.com/cosmos/cosmos-sdk/x/distribution"
	"github.com/cosmos/cosmos-sdk/x/genutil"
	"github.com/cosmos/cosmos-sdk/x/gov"
	"github.com/cosmos/cosmos-sdk/x/mint"
	"github.com/cosmos/cosmos-sdk/x/params"
	"github.com/cosmos/cosmos-sdk/x/slashing"
	"github.com/cosmos/cosmos-sdk/x/staking"

	"io"
)

const (
	AppName       = "AishaApp"
	AccountPrefix = "aisha"
	NativeDenom   = "uash"
	GovDenom      = "ugovernance"
)

var (
	DefaultNodeHome string
	ModuleBasics    module.BasicManager
)

func init() {
	userHomeDir, _ := os.UserHomeDir()
	DefaultNodeHome = filepath.Join(userHomeDir, ".aisha")

	ModuleBasics = module.NewBasicManager(
		auth.AppModuleBasic{},
		genutil.AppModuleBasic{},
		bank.AppModuleBasic{},
		staking.AppModuleBasic{},
		mint.AppModuleBasic{},
		distribution.AppModuleBasic{},
		gov.NewAppModuleBasic(nil),
		params.AppModuleBasic{},
		crisis.AppModuleBasic{},
		slashing.AppModuleBasic{},
		consensus.AppModuleBasic{},
	)
}

// EncodingConfig specifies the concrete encoding types to use.
type EncodingConfig struct {
	InterfaceRegistry codectypes.InterfaceRegistry
	Codec             codec.Codec
	TxConfig          client.TxConfig
	Amino             *codec.LegacyAmino
	AccountRetriever  client.AccountRetriever
}

// MakeEncodingConfig creates the encoding config for the app.
func MakeEncodingConfig() EncodingConfig {
	amino := codec.NewLegacyAmino()
	interfaceRegistry := codectypes.NewInterfaceRegistry()
	cdc := codec.NewProtoCodec(interfaceRegistry)

	ModuleBasics.RegisterLegacyAminoCodec(amino)
	ModuleBasics.RegisterInterfaces(interfaceRegistry)

	return EncodingConfig{
		InterfaceRegistry: interfaceRegistry,
		Codec:             cdc,
		TxConfig:          authtx.NewTxConfig(cdc, authtx.DefaultSignModes),
		Amino:             amino,
		AccountRetriever:  authtypes.AccountRetriever{},
	}
}

// AishaApp extends an ABCI application with Cosmos SDK modules.
type AishaApp struct {
	*baseapp.BaseApp

	cdc               codec.Codec
	interfaceRegistry codectypes.InterfaceRegistry

	// Module keepers
	AccountKeeper authkeeper.AccountKeeper
	BankKeeper    bankkeeper.Keeper
}

// NewAishaApp returns a reference to a new AishaApp.
func NewAishaApp(
	logger log.Logger,
	db dbm.DB,
	traceStore io.Writer,
	loadLatest bool,
	appOpts servertypes.AppOptions,
	baseAppOptions ...func(*baseapp.BaseApp),
) *AishaApp {
	encodingConfig := MakeEncodingConfig()

	bApp := baseapp.NewBaseApp(
		AppName,
		logger,
		db,
		nil, // TxDecoder set later
		baseAppOptions...,
	)
	bApp.SetVersion("0.1.0")
	bApp.SetInterfaceRegistry(encodingConfig.InterfaceRegistry)

	app := &AishaApp{
		BaseApp:           bApp,
		cdc:               encodingConfig.Codec,
		interfaceRegistry: encodingConfig.InterfaceRegistry,
	}

	// NOTE: This is a scaffold placeholder.
	// Full module wiring (keeper initialization, store keys, router setup)
	// will be generated by Ignite CLI or manually completed.
	// The binary compiles but requires `ignite scaffold chain` for full
	// keeper wiring, genesis state, and module registration.

	if loadLatest {
		// Load latest state from DB
	}

	return app
}

// ExportAppStateAndValidators exports the application state.
func (app *AishaApp) ExportAppStateAndValidators(
	forZeroHeight bool,
	jailAllowedAddrs []string,
	modulesToExport []string,
) (servertypes.ExportedApp, error) {
	return servertypes.ExportedApp{}, nil
}

// RegisterAPIRoutes registers core and module gRPC gateway routes.
func (app *AishaApp) RegisterAPIRoutes(apiSvr *api.Server, _ serverconfig.APIConfig) {
	clientCtx := apiSvr.ClientCtx
	authtx.RegisterGRPCGatewayRoutes(clientCtx, apiSvr.GRPCGatewayRouter)
	cmtservice.RegisterGRPCGatewayRoutes(clientCtx, apiSvr.GRPCGatewayRouter)
	nodeservice.RegisterGRPCGatewayRoutes(clientCtx, apiSvr.GRPCGatewayRouter)
	ModuleBasics.RegisterGRPCGatewayRoutes(clientCtx, apiSvr.GRPCGatewayRouter)
}

// RegisterTxService registers the Cosmos SDK tx service.
func (app *AishaApp) RegisterTxService(clientCtx client.Context) {
	authtx.RegisterTxService(app.GRPCQueryRouter(), clientCtx, app.Simulate, app.interfaceRegistry)
}

// RegisterTendermintService registers CometBFT query services.
func (app *AishaApp) RegisterTendermintService(clientCtx client.Context) {
	cmtApp := sdkserver.NewCometABCIWrapper(app)
	cmtservice.RegisterTendermintService(
		clientCtx,
		app.GRPCQueryRouter(),
		app.interfaceRegistry,
		cmtApp.Query,
	)
}

// RegisterNodeService registers node query services.
func (app *AishaApp) RegisterNodeService(clientCtx client.Context, cfg serverconfig.Config) {
	nodeservice.RegisterNodeService(clientCtx, app.GRPCQueryRouter(), cfg)
}
