/**
 * File-safety utilities for IDE instruction generation.
 *
 * Three guarantees:
 *  1. User-owned files (no auto-gen header) are NEVER overwritten.
 *  2. Managed files have a preserved <!-- aisha:user-section --> block
 *     that survives every regeneration.
 *  3. Every overwrite creates a timestamped backup in .aisha/backups/
 *     (last 5 backups per file are kept).
 *
 * @module
 */

import * as vscode from "vscode";
import { getAutoGenMarker } from "./registry";

export const USER_SECTION_OPEN = "<!-- aisha:user-section:start -->";
export const USER_SECTION_CLOSE = "<!-- aisha:user-section:end -->";

const BACKUPS_PER_FILE = 5;

/**
 * Returns true if content contains the AISHA auto-generated header marker.
 * Files without the marker are considered user-owned and must never be overwritten.
 */
export function hasAutoGenHeader(content: string): boolean {
  return content.includes(getAutoGenMarker());
}

/**
 * Extract the user-section block from existing content. Returns the inner text
 * (between the markers, exclusive) or null when no block is present.
 */
export function extractUserSection(content: string): string | null {
  const openIdx = content.indexOf(USER_SECTION_OPEN);
  if (openIdx === -1) return null;
  const afterOpen = openIdx + USER_SECTION_OPEN.length;
  const closeIdx = content.indexOf(USER_SECTION_CLOSE, afterOpen);
  if (closeIdx === -1) return null;
  return content.slice(afterOpen, closeIdx);
}

/**
 * Inject (or replace) a user-section block in generated content.
 * Block is placed just before the metadata footer (`<!-- gen:metadata ... -->`),
 * or appended at the end when no footer is present.
 */
export function injectUserSection(generated: string, userInner: string): string {
  const block = `${USER_SECTION_OPEN}${userInner}${USER_SECTION_CLOSE}\n`;

  if (generated.includes(USER_SECTION_OPEN)) {
    return generated.replace(
      new RegExp(`${escapeRegex(USER_SECTION_OPEN)}[\\s\\S]*?${escapeRegex(USER_SECTION_CLOSE)}\\n?`),
      block,
    );
  }

  const footerMatch = generated.match(/<!-- gen:metadata [\s\S]*? -->/);
  if (footerMatch && footerMatch.index !== undefined) {
    return generated.slice(0, footerMatch.index) + block + "\n" + generated.slice(footerMatch.index);
  }

  const trimmed = generated.replace(/\n+$/, "");
  return `${trimmed}\n\n${block}`;
}

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function defaultUserSectionInner(): string {
  return "\n<!--\n  Anything between these markers is preserved across regenerations.\n  Add project-specific notes, overrides, or constraints that Claude/Copilot\n  should always see. Lines outside this block may be regenerated by Dirigent.\n-->\n";
}

/**
 * Result of a safe-write attempt.
 */
export interface SafeWriteOutcome {
  outcome: "written" | "skipped-identical" | "refused-user-owned" | "backup-failed";
  backupPath?: string;
  preservedUserSection: boolean;
}

/**
 * Safely write a generated file. Enforces the three guarantees from the module
 * docstring. Caller is responsible for `stripVolatile` identity check before
 * calling — this function performs the safety checks regardless.
 */
export async function safeWrite(
  rootUri: vscode.Uri,
  outputPath: string,
  newContent: string,
  existingContent: string | null,
): Promise<SafeWriteOutcome> {
  // 1. User-owned guard: refuse to overwrite files without the auto-gen header.
  if (existingContent !== null && !hasAutoGenHeader(existingContent)) {
    return { outcome: "refused-user-owned", preservedUserSection: false };
  }

  // 2. User-section preservation (and seed empty template for fresh files).
  let contentToWrite = newContent;
  let preserved = false;
  if (existingContent !== null) {
    const userInner = extractUserSection(existingContent);
    if (userInner !== null && userInner.trim().length > 0) {
      contentToWrite = injectUserSection(newContent, userInner);
      preserved = true;
    }
  }
  if (!contentToWrite.includes(USER_SECTION_OPEN)) {
    contentToWrite = injectUserSection(contentToWrite, defaultUserSectionInner());
  }

  // 3. Backup before overwrite.
  let backupPath: string | undefined;
  if (existingContent !== null) {
    try {
      backupPath = await writeBackup(rootUri, outputPath, existingContent);
      await rotateBackups(rootUri, outputPath);
    } catch {
      // Backup failure must not block legitimate regeneration, but surface it.
      return { outcome: "backup-failed", preservedUserSection: preserved };
    }
  }

  // 4. Write.
  const fileUri = vscode.Uri.joinPath(rootUri, outputPath);
  const dirUri = vscode.Uri.joinPath(fileUri, "..");
  try {
    await vscode.workspace.fs.createDirectory(dirUri);
  } catch {
    // exists
  }
  await vscode.workspace.fs.writeFile(fileUri, new TextEncoder().encode(contentToWrite));

  return { outcome: "written", backupPath, preservedUserSection: preserved };
}

/**
 * Convenience wrapper around `safeWrite` that resolves the existing file from
 * the workspace itself. Call sites do not need to pre-read the file.
 */
export async function safeWriteFromUri(
  rootUri: vscode.Uri,
  outputPath: string,
  newContent: string,
): Promise<SafeWriteOutcome> {
  const fileUri = vscode.Uri.joinPath(rootUri, outputPath);
  let existingContent: string | null = null;
  try {
    const buf = await vscode.workspace.fs.readFile(fileUri);
    existingContent = new TextDecoder().decode(buf);
  } catch {
    // file doesn't exist
  }
  return safeWrite(rootUri, outputPath, newContent, existingContent);
}

/**
 * Variant for non-markdown writes (e.g. JSON config) that need backup but not
 * user-section preservation. Always writes; only the backup + rotation is
 * shared with the markdown safeWrite path. Refuse-user-owned is skipped
 * because structured JSON files don't carry the auto-gen marker.
 */
export async function safeWriteJson(
  rootUri: vscode.Uri,
  outputPath: string,
  newContent: string,
): Promise<{ outcome: "written" | "backup-failed"; backupPath?: string }> {
  const fileUri = vscode.Uri.joinPath(rootUri, outputPath);
  let backupPath: string | undefined;
  try {
    const existing = await vscode.workspace.fs.readFile(fileUri);
    backupPath = await writeBackup(rootUri, outputPath, new TextDecoder().decode(existing));
    await rotateBackups(rootUri, outputPath);
  } catch (err) {
    // File may simply not exist; only treat actual backup failures as fatal.
    if (err && typeof err === "object" && "code" in err && (err as { code: string }).code !== "FileNotFound") {
      return { outcome: "backup-failed" };
    }
  }
  const dirUri = vscode.Uri.joinPath(fileUri, "..");
  try {
    await vscode.workspace.fs.createDirectory(dirUri);
  } catch {
    // exists
  }
  await vscode.workspace.fs.writeFile(fileUri, new TextEncoder().encode(newContent));
  return { outcome: "written", backupPath };
}

/**
 * Safely write an executable file (shell / python / node script). Mirror of the
 * CLI twin `safeWriteExecutableSync` in scripts/lib/ide-instructions-safety.mjs.
 *
 * Unlike {@link safeWrite}, there is NO HTML user-section marker — those are
 * syntactically wrong for shell/python and would corrupt the script. The
 * user-content protection here is purely the timestamped backup plus the
 * skip-when-byte-identical short-circuit. (vscode.workspace.fs has no chmod, so
 * the +x bit is set by the CLI writer; the extension relies on settings.json
 * invoking the script via `bash`/`node`.)
 */
export async function safeWriteExecutable(
  rootUri: vscode.Uri,
  outputPath: string,
  newContent: string,
): Promise<{ outcome: "written" | "skipped-identical" | "backup-failed"; backupPath?: string }> {
  const fileUri = vscode.Uri.joinPath(rootUri, outputPath);

  let existingContent: string | null = null;
  try {
    const buf = await vscode.workspace.fs.readFile(fileUri);
    existingContent = new TextDecoder().decode(buf);
  } catch {
    // file doesn't exist
  }

  if (existingContent !== null && existingContent === newContent) {
    return { outcome: "skipped-identical" };
  }

  let backupPath: string | undefined;
  if (existingContent !== null) {
    try {
      backupPath = await writeBackup(rootUri, outputPath, existingContent);
      await rotateBackups(rootUri, outputPath);
    } catch {
      return { outcome: "backup-failed" };
    }
  }

  const dirUri = vscode.Uri.joinPath(fileUri, "..");
  try {
    await vscode.workspace.fs.createDirectory(dirUri);
  } catch {
    // exists
  }
  await vscode.workspace.fs.writeFile(fileUri, new TextEncoder().encode(newContent));

  return { outcome: "written", backupPath };
}

/**
 * Write a timestamped backup to `.aisha/backups/<flattened-path>.<ISO>.bak`.
 */
async function writeBackup(
  rootUri: vscode.Uri,
  outputPath: string,
  content: string,
): Promise<string> {
  const backupsDir = vscode.Uri.joinPath(rootUri, ".aisha", "backups");
  try {
    await vscode.workspace.fs.createDirectory(backupsDir);
  } catch {
    // exists
  }
  const flat = outputPath.replace(/[/\\]/g, "__");
  const stamp = new Date().toISOString().replace(/[:.]/g, "-");
  const fileName = `${flat}.${stamp}.bak`;
  const target = vscode.Uri.joinPath(backupsDir, fileName);
  await vscode.workspace.fs.writeFile(target, new TextEncoder().encode(content));
  return fileName;
}

/**
 * Keep only the last BACKUPS_PER_FILE backups per source file.
 */
async function rotateBackups(rootUri: vscode.Uri, outputPath: string): Promise<void> {
  const backupsDir = vscode.Uri.joinPath(rootUri, ".aisha", "backups");
  const flat = outputPath.replace(/[/\\]/g, "__");
  let entries: [string, vscode.FileType][] = [];
  try {
    entries = await vscode.workspace.fs.readDirectory(backupsDir);
  } catch {
    return;
  }
  const matches = entries
    .filter(([name, type]) => type === vscode.FileType.File && name.startsWith(`${flat}.`) && name.endsWith(".bak"))
    .map(([name]) => name)
    .sort();
  const stale = matches.slice(0, Math.max(0, matches.length - BACKUPS_PER_FILE));
  for (const name of stale) {
    try {
      await vscode.workspace.fs.delete(vscode.Uri.joinPath(backupsDir, name));
    } catch {
      // best effort
    }
  }
}
