#!/usr/bin/env bash
# =============================================================================
# metrics.sh — Prometheus textfile metrics pro shell skripty
# =============================================================================
# Source via: . "$SCRIPT_DIR/lib/metrics.sh"
#
# Env vars:
#   AISHA_METRICS_DIR=...    (default: <repo>/.metrics)
#   AISHA_METRICS_DISABLE=1  → no-op
#
# Public API:
#   metrics_counter   <name> <value> [k1 v1 k2 v2 ...]
#   metrics_gauge     <name> <value> [k1 v1 k2 v2 ...]
#   metrics_phase_start  <name>      → records start time pro metrics_phase_end
#   metrics_phase_end    <name> <result>  → emitne duration histogram
#   metrics_flush     [filename]      → write .prom file
# =============================================================================

if [[ -n "${_AISHA_METRICS_LOADED:-}" ]]; then return 0 2>/dev/null || exit 0; fi
_AISHA_METRICS_LOADED=1

_AISHA_METRICS_DIR="${AISHA_METRICS_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)/.metrics}"
_AISHA_METRICS_DISABLE="${AISHA_METRICS_DISABLE:-0}"
_AISHA_METRICS_RUN_ID="$(date -u +%Y-%m-%dT%H-%M-%S)Z-$$"
_AISHA_METRICS_BUFFER=""

_format_labels() {
  # k1 v1 k2 v2 → {k1="v1",k2="v2"}
  local pairs=""
  while [[ $# -ge 2 ]]; do
    local k="$1" v="$2"; shift 2
    # Escape backslash + double quote (basic, no newline escaping)
    v="${v//\\/\\\\}"
    v="${v//\"/\\\"}"
    if [[ -n "$pairs" ]]; then pairs+=","; fi
    pairs+="${k}=\"${v}\""
  done
  if [[ -n "$pairs" ]]; then echo "{${pairs}}"; fi
}

_metric_record() {
  local type="$1"; local name="$2"; local value="$3"; shift 3
  if [[ "$_AISHA_METRICS_DISABLE" == "1" ]]; then return 0; fi
  local labels
  labels=$(_format_labels "$@")
  _AISHA_METRICS_BUFFER+="${type}|${name}|${labels}|${value}"$'\n'
}

metrics_counter() { _metric_record counter "$@"; }
metrics_gauge()   { _metric_record gauge "$@"; }

# Phase timer
metrics_phase_start() {
  local name="$1"
  local var="_AISHA_METRICS_PHASE__${name//[^a-zA-Z0-9_]/_}"
  eval "$var=$(date +%s)"
}

metrics_phase_end() {
  local name="$1"; local result="${2:-success}"
  local var="_AISHA_METRICS_PHASE__${name//[^a-zA-Z0-9_]/_}"
  local t0="${!var:-0}"
  local duration=$(( $(date +%s) - t0 ))
  metrics_gauge "aisha_cold_start_phase_duration_seconds" "$duration" phase "$name" result "$result"
  metrics_counter "aisha_cold_start_phase_total" 1 phase "$name" result "$result"
  unset "$var"
}

metrics_flush() {
  if [[ "$_AISHA_METRICS_DISABLE" == "1" ]]; then return 0; fi
  if [[ -z "$_AISHA_METRICS_BUFFER" ]]; then return 0; fi

  local filename="${1:-cold-start-${_AISHA_METRICS_RUN_ID}.prom}"
  mkdir -p "$_AISHA_METRICS_DIR"
  local out_path="${_AISHA_METRICS_DIR}/${filename}"

  # Group by metric name → single HELP+TYPE per metric
  local out=""
  local seen=""
  while IFS='|' read -r type name labels value; do
    [[ -z "$type" ]] && continue
    if [[ ",$seen," != *",$name,"* ]]; then
      out+="# HELP $name (auto-generated by aisha cold-start metrics)"$'\n'
      out+="# TYPE $name $type"$'\n'
      seen+=",$name"
    fi
    out+="${name}${labels} ${value}"$'\n'
  done <<< "$_AISHA_METRICS_BUFFER"

  echo "$out" > "$out_path"
  echo "$out_path"
}
