// =============================================================================
// metrics.mjs — Prometheus textfile metrics emitter pro cold-start
// =============================================================================
// Píše do `.metrics/<run-id>.prom` soubor v Prometheus exposition format.
// Pickup: `node_exporter --collector.textfile.directory=<dir>` (na hostu) nebo
// manual scrape přes `curl file://...`.
//
// Env vars:
//   AISHA_METRICS_DIR=/path/to/.metrics  (default: <repo>/.metrics)
//   AISHA_METRICS_DISABLE=1              → no-op všechny calls
//
// Usage:
//   import { metrics } from "./lib/metrics.mjs";
//   metrics.counter("aisha_cold_start_phase_total", 1, { phase: "step5", result: "success" });
//   metrics.histogram("aisha_cold_start_phase_duration_seconds", 12.5, { phase: "step5" });
//   metrics.flush();   // write all accumulated to .prom file
// =============================================================================

import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { resolve, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "../..");
const METRICS_DIR = process.env.AISHA_METRICS_DIR || join(REPO_ROOT, ".metrics");
const DISABLED = process.env.AISHA_METRICS_DISABLE === "1";
const RUN_ID = new Date().toISOString().replace(/[:.]/g, "-");

// In-memory buffer of metric records
const records = [];

function escapeLabel(v) {
  return String(v).replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n");
}

function fmtLabels(labels) {
  if (!labels || Object.keys(labels).length === 0) return "";
  const entries = Object.entries(labels)
    .map(([k, v]) => `${k}="${escapeLabel(v)}"`)
    .join(",");
  return `{${entries}}`;
}

export const metrics = {
  // Counter — monotonically increasing value
  counter(name, value = 1, labels = {}) {
    if (DISABLED) return;
    records.push({ type: "counter", name, value, labels });
  },

  // Gauge — point-in-time value (can go up/down)
  gauge(name, value, labels = {}) {
    if (DISABLED) return;
    records.push({ type: "gauge", name, value, labels });
  },

  // Histogram observation — emit as plain summary line
  // (real histogram needs bucket pre-decl; pro simplicity používáme single observation
  //  metric, jak doporučuje textfile collector convention)
  histogram(name, value, labels = {}) {
    if (DISABLED) return;
    records.push({ type: "gauge", name, value, labels });
  },

  // Flush all accumulated records to .prom file
  flush(filename) {
    if (DISABLED) return null;
    if (records.length === 0) return null;

    if (!existsSync(METRICS_DIR)) {
      mkdirSync(METRICS_DIR, { recursive: true });
    }

    // Group by metric name to emit single # HELP + # TYPE per metric
    const byName = new Map();
    for (const r of records) {
      if (!byName.has(r.name)) byName.set(r.name, { type: r.type, lines: [] });
      const labels = fmtLabels(r.labels);
      byName.get(r.name).lines.push(`${r.name}${labels} ${r.value}`);
    }

    const out = [];
    for (const [name, { type, lines }] of byName) {
      out.push(`# HELP ${name} (auto-generated by aisha cold-start metrics)`);
      out.push(`# TYPE ${name} ${type}`);
      out.push(...lines);
      out.push("");
    }

    const path = join(METRICS_DIR, filename || `cold-start-${RUN_ID}.prom`);
    writeFileSync(path, out.join("\n"));
    return path;
  },

  // Convenience: phase timer wrapper
  async phase(name, labels, fn) {
    const t0 = Date.now();
    try {
      const result = await fn();
      const duration = (Date.now() - t0) / 1000;
      metrics.histogram("aisha_cold_start_phase_duration_seconds", duration, { phase: name, result: "success", ...labels });
      metrics.counter("aisha_cold_start_phase_total", 1, { phase: name, result: "success", ...labels });
      return result;
    } catch (e) {
      const duration = (Date.now() - t0) / 1000;
      metrics.histogram("aisha_cold_start_phase_duration_seconds", duration, { phase: name, result: "error", ...labels });
      metrics.counter("aisha_cold_start_phase_total", 1, { phase: name, result: "error", ...labels });
      throw e;
    }
  },
};

export default metrics;
